
#pragma once

volatile LONG TransparentModeTrapListLock;

#define MSR_IA32_TIME_STAMP_COUNTER 0x10

#define RAND_MAX 0x7fff

#define MAXIMUM_NUMBER_OF_THREAD_INFORMATION_FOR_TRANSPARENT_MODE_TRAPS 500

typedef struct _TRANSPARENCY_MEASUREMENTS {
  UINT64 CpuidAverage;
  UINT64 CpuidStandardDeviation;
  UINT64 CpuidMedian;
  UINT64 RdtscAverage;
  UINT64 RdtscStandardDeviation;
  UINT64 RdtscMedian;
  LIST_ENTRY ProcessList;
} TRANSPARENCY_MEASUREMENTS, *PTRANSPARENCY_MEASUREMENTS;

typedef struct _TRANSPARENCY_PROCESS {
  UINT32 ProcessId;
  PVOID ProcessName;
  PVOID BufferAddress;
  BOOLEAN TrueIfProcessIdAndFalseIfProcessName;
  LIST_ENTRY OtherProcesses;
} TRANSPARENCY_PROCESS, *PTRANSPARENCY_PROCESS;

typedef struct _TRANSPARENT_MODE_PROCESS_THREAD_INFORMATION {
  union {
    UINT64 asUInt;

    struct {
      UINT32 ProcessId;
      UINT32 ThreadId;
    } Fields;
  };
} TRANSPARENT_MODE_PROCESS_THREAD_INFORMATION,
    *PTRANSPARENT_MODE_PROCESS_THREAD_INFORMATION;

typedef struct _TRANSPARENT_MODE_CONTEXT_PARAMS {
  UINT64 OptionalParam1;
  UINT64 OptionalParam2;
  UINT64 OptionalParam3;
  UINT64 OptionalParam4;
} TRANSPARENT_MODE_CONTEXT_PARAMS, *PTRANSPARENT_MODE_CONTEXT_PARAMS;

typedef struct _TRANSPARENT_MODE_TRAP_FLAG_STATE {
  UINT32 NumberOfItems;
  TRANSPARENT_MODE_PROCESS_THREAD_INFORMATION ThreadInformation
      [MAXIMUM_NUMBER_OF_THREAD_INFORMATION_FOR_TRANSPARENT_MODE_TRAPS];
  UINT64
  Context[MAXIMUM_NUMBER_OF_THREAD_INFORMATION_FOR_TRANSPARENT_MODE_TRAPS];
  TRANSPARENT_MODE_CONTEXT_PARAMS
  Params[MAXIMUM_NUMBER_OF_THREAD_INFORMATION_FOR_TRANSPARENT_MODE_TRAPS];
} TRANSPARENT_MODE_TRAP_FLAG_STATE, *PTRANSPARENT_MODE_TRAP_FLAG_STATE;

VOID TransparentCPUID(INT32 CpuInfo[], PGUEST_REGS Regs);
BOOLEAN TransparentSetTrapFlagAfterSyscall(
    VIRTUAL_MACHINE_STATE *VCpu, UINT32 ProcessId, UINT32 ThreadId,
    UINT64 Context, TRANSPARENT_MODE_CONTEXT_PARAMS *Params);
BOOLEAN TransparentCheckAndHandleAfterSyscallTrapFlags(
    VIRTUAL_MACHINE_STATE *VCpu, UINT32 ProcessId, UINT32 ThreadId);
VOID TransparentCallbackHandleAfterSyscall(
    VIRTUAL_MACHINE_STATE *VCpu, UINT32 ProcessId, UINT32 ThreadId,
    UINT64 Context, TRANSPARENT_MODE_CONTEXT_PARAMS *Params);
