
#pragma once

#define DEBUGGER_VMCALL_VM_EXIT_HALT_SYSTEM \
  (TOP_LEVEL_DRIVERS_VMCALL_STARTING_NUMBER + 0x00000001)

#define DEBUGGER_VMCALL_VM_EXIT_HALT_SYSTEM_AS_A_RESULT_OF_TRIGGERING_EVENT \
  (TOP_LEVEL_DRIVERS_VMCALL_STARTING_NUMBER + 0x00000002)

#define DEBUGGER_VMCALL_SIGNAL_DEBUGGER_EXECUTION_FINISHED \
  (TOP_LEVEL_DRIVERS_VMCALL_STARTING_NUMBER + 0x00000003)

#define DEBUGGER_VMCALL_SEND_MESSAGES_TO_DEBUGGER \
  (TOP_LEVEL_DRIVERS_VMCALL_STARTING_NUMBER + 0x00000004)

#define DEBUGGER_VMCALL_SEND_GENERAL_BUFFER_TO_DEBUGGER \
  (TOP_LEVEL_DRIVERS_VMCALL_STARTING_NUMBER + 0x00000005)
BOOLEAN DebuggerVmcallHandler(UINT32 CoreId, UINT64 VmcallNumber,
                              UINT64 OptionalParam1, UINT64 OptionalParam2,
                              UINT64 OptionalParam3);
