
#pragma once

#define DEBUGGER_HALTED_CORE_TASK_TEST 0x00000001

#define DEBUGGER_HALTED_CORE_TASK_RUN_VMCALL 0x00000002

#define DEBUGGER_HALTED_CORE_TASK_SET_PROCESS_INTERCEPTION 0x00000003

#define DEBUGGER_HALTED_CORE_TASK_SET_THREAD_INTERCEPTION 0x00000004

#define DEBUGGER_HALTED_CORE_TASK_CHANGE_MSR_BITMAP_READ 0x00000005

#define DEBUGGER_HALTED_CORE_TASK_CHANGE_MSR_BITMAP_WRITE 0x00000006

#define DEBUGGER_HALTED_CORE_TASK_CHANGE_IO_BITMAP 0x00000007

#define DEBUGGER_HALTED_CORE_TASK_SET_RDPMC_EXITING 0x00000008

#define DEBUGGER_HALTED_CORE_TASK_SET_RDTSC_EXITING 0x00000009

#define DEBUGGER_HALTED_CORE_TASK_ENABLE_MOV_TO_DEBUG_REGS_EXITING 0x0000000a

#define DEBUGGER_HALTED_CORE_TASK_SET_EXCEPTION_BITMAP 0x0000000b

#define DEBUGGER_HALTED_CORE_TASK_ENABLE_EXTERNAL_INTERRUPT_EXITING 0x0000000c

#define DEBUGGER_HALTED_CORE_TASK_ENABLE_MOV_TO_CONTROL_REGS_EXITING 0x0000000d

#define DEBUGGER_HALTED_CORE_TASK_ENABLE_SYSCALL_HOOK_EFER 0x0000000e

#define DEBUGGER_HALTED_CORE_TASK_INVEPT_ALL_CONTEXTS 0x0000000f

#define DEBUGGER_HALTED_CORE_TASK_INVEPT_SINGLE_CONTEXT 0x00000010

#define DEBUGGER_HALTED_CORE_TASK_UNSET_EXCEPTION_BITMAP 0x00000011

#define DEBUGGER_HALTED_CORE_TASK_UNHOOK_SINGLE_PAGE 0x00000012

#define DEBUGGER_HALTED_CORE_TASK_DISABLE_EXTERNAL_INTERRUPT_EXITING_ONLY_TO_CLEAR_INTERRUPT_COMMANDS \
  0x00000013

#define DEBUGGER_HALTED_CORE_TASK_RESET_MSR_BITMAP_READ 0x00000014

#define DEBUGGER_HALTED_CORE_TASK_RESET_MSR_BITMAP_WRITE 0x00000015

#define DEBUGGER_HALTED_CORE_TASK_RESET_EXCEPTION_BITMAP_ONLY_ON_CLEARING_EXCEPTION_EVENTS \
  0x00000016

#define DEBUGGER_HALTED_CORE_TASK_RESET_IO_BITMAP 0x00000017

#define DEBUGGER_HALTED_CORE_TASK_DISABLE_RDTSC_EXITING_ONLY_FOR_TSC_EVENTS \
  0x00000018

#define DEBUGGER_HALTED_CORE_TASK_UNSET_RDPMC_EXITING 0x00000019

#define DEBUGGER_HALTED_CORE_TASK_DISABLE_SYSCALL_HOOK_EFER 0x0000001a

#define DEBUGGER_HALTED_CORE_TASK_DISABLE_MOV_TO_HW_DR_EXITING_ONLY_FOR_DR_EVENTS \
  0x0000001b

#define DEBUGGER_HALTED_CORE_TASK_DISABLE_MOV_TO_CR_EXITING_ONLY_FOR_CR_EVENTS \
  0x0000001c
BOOLEAN HaltedCoreBroadcastTaskAllCores(PROCESSOR_DEBUGGING_STATE *DbgState,
                                        UINT64 TargetTask,
                                        BOOLEAN LockAgainAfterTask,
                                        BOOLEAN Synchronize, PVOID Context);
VOID HaltedCoreRunTaskOnSingleCore(UINT32 TargetCoreId, UINT64 TargetTask,
                                   BOOLEAN LockAgainAfterTask, PVOID Context);
VOID HaltedCorePerformTargetTask(PROCESSOR_DEBUGGING_STATE *DbgState,
                                 UINT64 TargetTask, PVOID Context);
