//
// Created by Admin on 28/05/2025.
//

#ifndef MCPX64DBG_ECHO_GEN_H
#define MCPX64DBG_ECHO_GEN_H

#include "pluginsdk/bridgemain.h"
#include "pluginsdk/_plugins.h"

#include "pluginsdk/_scriptapi_argument.h"
#include "pluginsdk/_scriptapi_assembler.h"
#include "pluginsdk/_scriptapi_bookmark.h"
#include "pluginsdk/_scriptapi_comment.h"
#include "pluginsdk/_scriptapi_debug.h"
#include "pluginsdk/_scriptapi_flag.h"
#include "pluginsdk/_scriptapi_function.h"
#include "pluginsdk/_scriptapi_gui.h"
#include "pluginsdk/_scriptapi_label.h"
#include "pluginsdk/_scriptapi_memory.h"
#include "pluginsdk/_scriptapi_misc.h"
#include "pluginsdk/_scriptapi_module.h"
#include "pluginsdk/_scriptapi_pattern.h"
#include "pluginsdk/_scriptapi_register.h"
#include "pluginsdk/_scriptapi_stack.h"
#include "pluginsdk/_scriptapi_symbol.h"

#include "pluginsdk/DeviceNameResolver/DeviceNameResolver.h"
#include "pluginsdk/jansson/jansson.h"
#include "pluginsdk/lz4/lz4file.h"
#include "pluginsdk/TitanEngine/TitanEngine.h"
#include "pluginsdk/XEDParse/XEDParse.h"

#ifdef _WIN64
#pragma comment(lib, "pluginsdk/x64dbg.lib")
#pragma comment(lib, "pluginsdk/x64bridge.lib")
#pragma comment(lib, "pluginsdk/DeviceNameResolver/DeviceNameResolver_x64.lib")
#pragma comment(lib, "pluginsdk/jansson/jansson_x64.lib")
#pragma comment(lib, "pluginsdk/lz4/lz4_x64.lib")
#pragma comment(lib, "pluginsdk/TitanEngine/TitanEngine_x64.lib")
#pragma comment(lib, "pluginsdk/XEDParse/XEDParse_x64.lib")
#else
#pragma comment(lib, "pluginsdk/x32dbg.lib")
#pragma comment(lib, "pluginsdk/x32bridge.lib")
#pragma comment(lib, "pluginsdk/DeviceNameResolver/DeviceNameResolver_x86.lib")
#pragma comment(lib, "pluginsdk/jansson/jansson_x86.lib")
#pragma comment(lib, "pluginsdk/lz4/lz4_x86.lib")
#pragma comment(lib, "pluginsdk/TitanEngine/TitanEngine_x86.lib")
#pragma comment(lib, "pluginsdk/XEDParse/XEDParse_x86.lib")
#endif //_WIN64问题是为
#pragma comment(lib, "shlwapi.lib")


#include <map>
#include <string>
#include <functional>

void dispatch(const std::string &path) {
    static const std::unordered_map<std::string, std::function<void()>> handlers{
	{"bridgemain.h/DbgGetThreadId",   [] { DbgGetThreadId(); }},
	{"_scriptapi_register.h/GetBX",   [] { Script::Register::GetBX(); }},
	{"_scriptapi_register.h/Get",   [] { Script::Register::Get(); }},
	{"_scriptapi_register.h/SetDR0",   [] { Script::Register::SetDR0(); }},
	{"_scriptapi_debug.h/DisableBreakpoint",   [] { Script::Debug::DisableBreakpoint(); }},
	{"bridgemain.h/DbgXrefDelAll",   [] { DbgXrefDelAll(); }},
	{"bridgemain.h/BridgeSettingGetUint",   [] { BridgeSettingGetUint(); }},
	{"bridgemain.h/DbgSetEncodeType",   [] { DbgSetEncodeType(); }},
	{"bridgemain.h/DbgFunctionGet",   [] { DbgFunctionGet(); }},
	{"_scriptapi_register.h/SetCDX",   [] { Script::Register::SetCDX(); }},
	{"bridgemain.h/BridgeGetDbgVersion",   [] { BridgeGetDbgVersion(); }},
	{"_scriptapi_register.h/SetESP",   [] { Script::Register::SetESP(); }},
	{"_scriptapi_debug.h/SetHardwareBreakpoint",   [] { Script::Debug::SetHardwareBreakpoint(); }},
	{"bridgemain.h/GuiAddFavouriteTool",   [] { GuiAddFavouriteTool(); }},
	{"_scriptapi_module.h/SizeFromAddr",   [] { Script::Module::SizeFromAddr(); }},
	{"bridgemain.h/GuiTypeAddNode",   [] { GuiTypeAddNode(); }},
	{"_scriptapi_label.h/GetList",   [] { Script::Label::GetList(); }},
	{"_scriptapi_register.h/GetECX",   [] { Script::Register::GetECX(); }},
	{"bridgemain.h/GuiMenuSetEntryName",   [] { GuiMenuSetEntryName(); }},
	{"_scriptapi_register.h/GetR13",   [] { Script::Register::GetR13(); }},
	{"bridgemain.h/DbgXrefAddMulti",   [] { DbgXrefAddMulti(); }},
	{"bridgemain.h/DbgGetEncodeTypeBuffer",   [] { DbgGetEncodeTypeBuffer(); }},
	{"_scriptapi_register.h/SetR12W",   [] { Script::Register::SetR12W(); }},
	{"_scriptapi_register.h/SetCSP",   [] { Script::Register::SetCSP(); }},
	{"_scriptapi_register.h/SetEDX",   [] { Script::Register::SetEDX(); }},
	{"_scriptapi_register.h/GetR14B",   [] { Script::Register::GetR14B(); }},
	{"_scriptapi_function.h/GetInfo",   [] { Script::Function::GetInfo(); }},
	{"bridgemain.h/DbgGetBookmarkAt",   [] { DbgGetBookmarkAt(); }},
	{"bridgemain.h/DbgGetBpList",   [] { DbgGetBpList(); }},
	{"_scriptapi_assembler.h/AssembleEx",   [] { Script::Assembler::AssembleEx(); }},
	{"bridgemain.h/GuiCloseApplication",   [] { GuiCloseApplication(); }},
	{"_scriptapi_register.h/SetR11W",   [] { Script::Register::SetR11W(); }},
	{"_scriptapi_debug.h/Stop",   [] { Script::Debug::Stop(); }},
	{"_scriptapi_register.h/SetDH",   [] { Script::Register::SetDH(); }},
	{"_scriptapi_register.h/SetEAX",   [] { Script::Register::SetEAX(); }},
	{"_scriptapi_assembler.h/Assemble",   [] { Script::Assembler::Assemble(); }},
	{"_scriptapi_flag.h/SetOF",   [] { Script::Flag::SetOF(); }},
	{"_scriptapi_register.h/SetRBP",   [] { Script::Register::SetRBP(); }},
	{"bridgemain.h/DbgIsDebugging",   [] { DbgIsDebugging(); }},
	{"_scriptapi_flag.h/SetSF",   [] { Script::Flag::SetSF(); }},
	{"bridgemain.h/GuiUpdateSideBar",   [] { GuiUpdateSideBar(); }},
	{"bridgemain.h/GuiGetDebuggeeNotes",   [] { GuiGetDebuggeeNotes(); }},
	{"_scriptapi_flag.h/GetZF",   [] { Script::Flag::GetZF(); }},
	{"_scriptapi_register.h/SetEBP",   [] { Script::Register::SetEBP(); }},
	{"bridgemain.h/GuiMenuClear",   [] { GuiMenuClear(); }},
	{"bridgemain.h/GuiSetDebugState",   [] { GuiSetDebugState(); }},
	{"_scriptapi_register.h/SetR13W",   [] { Script::Register::SetR13W(); }},
	{"bridgemain.h/DbgScriptUnload",   [] { DbgScriptUnload(); }},
	{"bridgemain.h/GuiLoadGraph",   [] { GuiLoadGraph(); }},
	{"_scriptapi_bookmark.h/DeleteRange",   [] { Script::Bookmark::DeleteRange(); }},
	{"_scriptapi_register.h/SetEDI",   [] { Script::Register::SetEDI(); }},
	{"_scriptapi_module.h/GetList",   [] { Script::Module::GetList(); }},
	{"_scriptapi_register.h/GetEBP",   [] { Script::Register::GetEBP(); }},
	{"_scriptapi_register.h/GetR14W",   [] { Script::Register::GetR14W(); }},
	{"_scriptapi_argument.h/Add",   [] { Script::Argument::Add(); }},
	{"bridgegraph.h/__debugbreak",   [] { __debugbreak(); }},
	{"bridgemain.h/GuiUpdateGraphView",   [] { GuiUpdateGraphView(); }},
	{"_scriptapi_argument.h/Get",   [] { Script::Argument::Get(); }},
	{"bridgemain.h/GuiRegisterScriptLanguage",   [] { GuiRegisterScriptLanguage(); }},
	{"_scriptapi_assembler.h/AssembleMemEx",   [] { Script::Assembler::AssembleMemEx(); }},
	{"_scriptapi_argument.h/DeleteRange",   [] { Script::Argument::DeleteRange(); }},
	{"_scriptapi_debug.h/Pause",   [] { Script::Debug::Pause(); }},
	{"_scriptapi_comment.h/GetList",   [] { Script::Comment::GetList(); }},
	{"bridgemain.h/BridgeSettingSet",   [] { BridgeSettingSet(); }},
	{"bridgemain.h/BridgeGetNtBuildNumber",   [] { BridgeGetNtBuildNumber(); }},
	{"bridgemain.h/BridgeUserDirectory",   [] { BridgeUserDirectory(); }},
	{"bridgemain.h/DbgScriptBpGet",   [] { DbgScriptBpGet(); }},
	{"bridgemain.h/GuiScriptAdd",   [] { GuiScriptAdd(); }},
	{"_scriptapi_flag.h/SetCF",   [] { Script::Flag::SetCF(); }},
	{"bridgemain.h/GuiMenuAddSeparator",   [] { GuiMenuAddSeparator(); }},
	{"_scriptapi_module.h/GetMainModuleSize",   [] { Script::Module::GetMainModuleSize(); }},
	{"bridgemain.h/GuiSelectionSet",   [] { GuiSelectionSet(); }},
	{"bridgemain.h/GuiReferenceGetRowCount",   [] { GuiReferenceGetRowCount(); }},
	{"bridgemain.h/DbgGetProcessHandle",   [] { DbgGetProcessHandle(); }},
	{"bridgemain.h/BridgeInit",   [] { BridgeInit(); }},
	{"_scriptapi_module.h/NameFromAddr",   [] { Script::Module::NameFromAddr(); }},
	{"bridgemain.h/GuiGetActiveView",   [] { GuiGetActiveView(); }},
	{"bridgemain.h/GuiMenuSetEntryHotkey",   [] { GuiMenuSetEntryHotkey(); }},
	{"bridgemain.h/GuiIsUpdateDisabled",   [] { GuiIsUpdateDisabled(); }},
	{"bridgemain.h/GuiUpdateThreadView",   [] { GuiUpdateThreadView(); }},
	{"_scriptapi_debug.h/DeleteBreakpoint",   [] { Script::Debug::DeleteBreakpoint(); }},
	{"bridgemain.h/DbgIsValidExpression",   [] { DbgIsValidExpression(); }},
	{"bridgemain.h/GuiDumpAt",   [] { GuiDumpAt(); }},
	{"_scriptapi_function.h/Add",   [] { Script::Function::Add(); }},
	{"_scriptapi_register.h/SetR10W",   [] { Script::Register::SetR10W(); }},
	{"bridgemain.h/DbgDelEncodeTypeRange",   [] { DbgDelEncodeTypeRange(); }},
	{"bridgemain.h/BridgeAlloc",   [] { BridgeAlloc(); }},
	{"_scriptapi_register.h/SetCIP",   [] { Script::Register::SetCIP(); }},
	{"_scriptapi_bookmark.h/GetInfo",   [] { Script::Bookmark::GetInfo(); }},
	{"bridgemain.h/GuiReferenceAddCommand",   [] { GuiReferenceAddCommand(); }},
	{"bridgemain.h/GuiDisasmAt",   [] { GuiDisasmAt(); }},
	{"bridgemain.h/GuiEnableLog",   [] { GuiEnableLog(); }},
	{"_scriptapi_register.h/GetAX",   [] { Script::Register::GetAX(); }},
	{"bridgemain.h/DbgScriptAbort",   [] { DbgScriptAbort(); }},
	{"bridgemain.h/DbgGetLabelAt",   [] { DbgGetLabelAt(); }},
	{"bridgemain.h/GuiInvalidateSymbolSource",   [] { GuiInvalidateSymbolSource(); }},
	{"bridgemain.h/DbgIsRunning",   [] { DbgIsRunning(); }},
	{"_scriptapi_register.h/GetR8",   [] { Script::Register::GetR8(); }},
	{"_scriptapi_register.h/GetDIL",   [] { Script::Register::GetDIL(); }},
	{"_scriptapi_stack.h/Push",   [] { Script::Stack::Push(); }},
	{"_scriptapi_module.h/SectionCountFromName",   [] { Script::Module::SectionCountFromName(); }},
	{"bridgemain.h/DbgFunctions",   [] { DbgFunctions(); }},
	{"bridgemain.h/GuiAddLogMessageHtml",   [] { GuiAddLogMessageHtml(); }},
	{"_scriptapi_assembler.h/AssembleMem",   [] { Script::Assembler::AssembleMem(); }},
	{"_scriptapi_register.h/SetR8",   [] { Script::Register::SetR8(); }},
	{"_scriptapi_register.h/SetCX",   [] { Script::Register::SetCX(); }},
	{"_scriptapi_register.h/SetDI",   [] { Script::Register::SetDI(); }},
	{"_scriptapi_gui.h/AddQWidgetTab",   [] { Script::Gui::AddQWidgetTab(); }},
	{"_scriptapi_register.h/GetDH",   [] { Script::Register::GetDH(); }},
	{"bridgemain.h/DbgIsRunLocked",   [] { DbgIsRunLocked(); }},
	{"_scriptapi_register.h/Set",   [] { Script::Register::Set(); }},
	{"_scriptapi_register.h/GetCH",   [] { Script::Register::GetCH(); }},
	{"_scriptapi_label.h/Clear",   [] { Script::Label::Clear(); }},
	{"_scriptapi_register.h/SetCBX",   [] { Script::Register::SetCBX(); }},
	{"_scriptapi_register.h/SetRDI",   [] { Script::Register::SetRDI(); }},
	{"_scriptapi_comment.h/GetInfo",   [] { Script::Comment::GetInfo(); }},
	{"_scriptapi_module.h/GetMainModulePath",   [] { Script::Module::GetMainModulePath(); }},
	{"bridgemain.h/DbgArgumentAdd",   [] { DbgArgumentAdd(); }},
	{"bridgemain.h/DbgLoopOverlaps",   [] { DbgLoopOverlaps(); }},
	{"bridgemain.h/GuiShowReferences",   [] { GuiShowReferences(); }},
	{"_scriptapi_register.h/GetRBX",   [] { Script::Register::GetRBX(); }},
	{"bridgegraph.h/Free",   [] { ::BridgeCFGraph::Free(); }},
	{"bridgemain.h/GuiTranslateText",   [] { GuiTranslateText(); }},
	{"_scriptapi_register.h/GetR11B",   [] { Script::Register::GetR11B(); }},
	{"bridgemain.h/DbgIsBpDisabled",   [] { DbgIsBpDisabled(); }},
	{"_scriptapi_register.h/GetRDI",   [] { Script::Register::GetRDI(); }},
	{"_scriptapi_label.h/GetInfo",   [] { Script::Label::GetInfo(); }},
	{"_scriptapi_gui.h/Refresh",   [] { Script::Gui::Refresh(); }},
	{"_scriptapi_function.h/GetList",   [] { Script::Function::GetList(); }},
	{"bridgemain.h/DbgGetArgTypeAt",   [] { DbgGetArgTypeAt(); }},
	{"_scriptapi_misc.h/RemoteGetProcAddress",   [] { Script::Misc::RemoteGetProcAddress(); }},
	{"bridgemain.h/GuiAddRecentFile",   [] { GuiAddRecentFile(); }},
	{"bridgemain.h/GuiScriptMsgyn",   [] { GuiScriptMsgyn(); }},
	{"_scriptapi_register.h/GetR13W",   [] { Script::Register::GetR13W(); }},
	{"_scriptapi_register.h/GetR10W",   [] { Script::Register::GetR10W(); }},
	{"_scriptapi_register.h/SetSP",   [] { Script::Register::SetSP(); }},
	{"_scriptapi_register.h/GetR15D",   [] { Script::Register::GetR15D(); }},
	{"bridgemain.h/DbgAnalyzeFunction",   [] { DbgAnalyzeFunction(); }},
	{"_scriptapi_register.h/GetR13D",   [] { Script::Register::GetR13D(); }},
	{"_scriptapi_register.h/GetSIL",   [] { Script::Register::GetSIL(); }},
	{"_scriptapi_memory.h/WriteByte",   [] { Script::Memory::WriteByte(); }},
	{"bridgemain.h/GuiSetGlobalNotes",   [] { GuiSetGlobalNotes(); }},
	{"bridgemain.h/GuiMenuSetName",   [] { GuiMenuSetName(); }},
	{"bridgemain.h/DbgSelChanged",   [] { DbgSelChanged(); }},
	{"_scriptapi_register.h/SetR11D",   [] { Script::Register::SetR11D(); }},
	{"_scriptapi_register.h/SetECX",   [] { Script::Register::SetECX(); }},
	{"_scriptapi_function.h/Get",   [] { Script::Function::Get(); }},
	{"bridgemain.h/GuiSelectInSymbolsTab",   [] { GuiSelectInSymbolsTab(); }},
	{"_scriptapi_memory.h/WritePtr",   [] { Script::Memory::WritePtr(); }},
	{"bridgemain.h/GuiReferenceSetCurrentTaskProgress",   [] { GuiReferenceSetCurrentTaskProgress(); }},
	{"bridgegraph.h/ToNodeList",   [] { ::BridgeCFNode::ToNodeList(); }},
	{"bridgemain.h/DbgGetThreadList",   [] { DbgGetThreadList(); }},
	{"_scriptapi_memory.h/ReadQword",   [] { Script::Memory::ReadQword(); }},
	{"_scriptapi_misc.h/ResolveLabel",   [] { Script::Misc::ResolveLabel(); }},
	{"_scriptapi_register.h/GetCCX",   [] { Script::Register::GetCCX(); }},
	{"_scriptapi_register.h/GetCBP",   [] { Script::Register::GetCBP(); }},
	{"_scriptapi_gui.h/SelectionGet",   [] { Script::Gui::SelectionGet(); }},
	{"_scriptapi_register.h/GetAL",   [] { Script::Register::GetAL(); }},
	{"_scriptapi_register.h/SetBX",   [] { Script::Register::SetBX(); }},
	{"_scriptapi_register.h/GetRSI",   [] { Script::Register::GetRSI(); }},
	{"bridgemain.h/GuiGetWindowHandle",   [] { GuiGetWindowHandle(); }},
	{"_scriptapi_register.h/GetR8W",   [] { Script::Register::GetR8W(); }},
	{"_scriptapi_register.h/SetR12D",   [] { Script::Register::SetR12D(); }},
	{"_scriptapi_pattern.h/Write",   [] { Script::Pattern::Write(); }},
	{"bridgemain.h/GuiSymbolRefreshCurrent",   [] { GuiSymbolRefreshCurrent(); }},
	{"_scriptapi_register.h/GetR10",   [] { Script::Register::GetR10(); }},
	{"bridgemain.h/GuiReferenceGetCellContent",   [] { GuiReferenceGetCellContent(); }},
	{"_scriptapi_register.h/SetCH",   [] { Script::Register::SetCH(); }},
	{"_scriptapi_register.h/SetAX",   [] { Script::Register::SetAX(); }},
	{"bridgemain.h/DbgGetBpxTypeAt",   [] { DbgGetBpxTypeAt(); }},
	{"_scriptapi_memory.h/GetBase",   [] { Script::Memory::GetBase(); }},
	{"bridgemain.h/GuiReferenceSetRowCount",   [] { GuiReferenceSetRowCount(); }},
	{"bridgemain.h/DbgSetCommentAt",   [] { DbgSetCommentAt(); }},
	{"_scriptapi_symbol.h/GetList",   [] { Script::Symbol::GetList(); }},
	{"_scriptapi_gui.h/SelectionGetEnd",   [] { Script::Gui::SelectionGetEnd(); }},
	{"bridgemain.h/GuiSelectionGet",   [] { GuiSelectionGet(); }},
	{"_scriptapi_register.h/GetR15W",   [] { Script::Register::GetR15W(); }},
	{"_scriptapi_memory.h/WriteDword",   [] { Script::Memory::WriteDword(); }},
	{"_scriptapi_argument.h/GetList",   [] { Script::Argument::GetList(); }},
	{"_scriptapi_register.h/SetR13D",   [] { Script::Register::SetR13D(); }},
	{"bridgemain.h/DbgXrefAdd",   [] { DbgXrefAdd(); }},
	{"_scriptapi_register.h/SetRSI",   [] { Script::Register::SetRSI(); }},
	{"_scriptapi_stack.h/Peek",   [] { Script::Stack::Peek(); }},
	{"bridgemain.h/GuiGraphAt",   [] { GuiGraphAt(); }},
	{"bridgemain.h/GuiScriptError",   [] { GuiScriptError(); }},
	{"_scriptapi_register.h/SetDR1",   [] { Script::Register::SetDR1(); }},
	{"_scriptapi_register.h/GetRBP",   [] { Script::Register::GetRBP(); }},
	{"bridgemain.h/DbgGetEncodeTypeAt",   [] { DbgGetEncodeTypeAt(); }},
	{"bridgemain.h/GuiUpdateDumpView",   [] { GuiUpdateDumpView(); }},
	{"bridgemain.h/DbgScriptGetLineType",   [] { DbgScriptGetLineType(); }},
	{"_scriptapi_memory.h/RemoteFree",   [] { Script::Memory::RemoteFree(); }},
	{"_scriptapi_register.h/SetRCX",   [] { Script::Register::SetRCX(); }},
	{"bridgemain.h/GuiAddLogMessage",   [] { GuiAddLogMessage(); }},
	{"bridgemain.h/GuiExecuteOnGuiThreadEx",   [] { GuiExecuteOnGuiThreadEx(); }},
	{"bridgemain.h/DbgClearAutoBookmarkRange",   [] { DbgClearAutoBookmarkRange(); }},
	{"_scriptapi_register.h/GetCSP",   [] { Script::Register::GetCSP(); }},
	{"bridgemain.h/GuiFoldDisassembly",   [] { GuiFoldDisassembly(); }},
	{"bridgemain.h/DbgLoopGet",   [] { DbgLoopGet(); }},
	{"_scriptapi_register.h/SetCBP",   [] { Script::Register::SetCBP(); }},
	{"_scriptapi_bookmark.h/Delete",   [] { Script::Bookmark::Delete(); }},
	{"_scriptapi_register.h/GetDR7",   [] { Script::Register::GetDR7(); }},
	{"bridgemain.h/DbgGetLoopTypeAt",   [] { DbgGetLoopTypeAt(); }},
	{"bridgemain.h/DbgWinEvent",   [] { DbgWinEvent(); }},
	{"bridgemain.h/GuiIsLogEnabled",   [] { GuiIsLogEnabled(); }},
	{"_scriptapi_register.h/SetDR3",   [] { Script::Register::SetDR3(); }},
	{"_scriptapi_register.h/GetEDI",   [] { Script::Register::GetEDI(); }},
	{"bridgemain.h/DbgClearAutoLabelRange",   [] { DbgClearAutoLabelRange(); }},
	{"_scriptapi_register.h/SetCL",   [] { Script::Register::SetCL(); }},
	{"bridgemain.h/DbgMemRead",   [] { DbgMemRead(); }},
	{"bridgemain.h/BridgeSettingGet",   [] { BridgeSettingGet(); }},
	{"bridgemain.h/GuiDumpAtN",   [] { GuiDumpAtN(); }},
	{"bridgemain.h/DbgMemMap",   [] { DbgMemMap(); }},
	{"bridgemain.h/DbgArgumentGet",   [] { DbgArgumentGet(); }},
	{"_scriptapi_register.h/GetCIP",   [] { Script::Register::GetCIP(); }},
	{"_scriptapi_register.h/SetCAX",   [] { Script::Register::SetCAX(); }},
	{"bridgemain.h/DbgScriptSetIp",   [] { DbgScriptSetIp(); }},
	{"_scriptapi_gui.h/InputLine",   [] { Script::Gui::InputLine(); }},
	{"bridgemain.h/GuiUpdateCallStack",   [] { GuiUpdateCallStack(); }},
	{"bridgemain.h/GuiRepaintTableView",   [] { GuiRepaintTableView(); }},
	{"_scriptapi_register.h/GetBP",   [] { Script::Register::GetBP(); }},
	{"_scriptapi_register.h/SetR15W",   [] { Script::Register::SetR15W(); }},
	{"bridgemain.h/DbgGetFunctionTypeAt",   [] { DbgGetFunctionTypeAt(); }},
	{"_scriptapi_register.h/GetSI",   [] { Script::Register::GetSI(); }},
	{"bridgemain.h/DbgLoopAdd",   [] { DbgLoopAdd(); }},
	{"bridgemain.h/DbgIsJumpGoingToExecute",   [] { DbgIsJumpGoingToExecute(); }},
	{"_scriptapi_gui.h/Message",   [] { Script::Gui::Message(); }},
	{"bridgemain.h/GuiScriptSetInfoLine",   [] { GuiScriptSetInfoLine(); }},
	{"_scriptapi_register.h/SetAL",   [] { Script::Register::SetAL(); }},
	{"bridgemain.h/GuiUpdateWatchView",   [] { GuiUpdateWatchView(); }},
	{"_scriptapi_module.h/EntryFromName",   [] { Script::Module::EntryFromName(); }},
	{"_scriptapi_module.h/SectionListFromAddr",   [] { Script::Module::SectionListFromAddr(); }},
	{"bridgemain.h/DbgAssembleAt",   [] { DbgAssembleAt(); }},
	{"bridgemain.h/GuiUpdateArgumentWidget",   [] { GuiUpdateArgumentWidget(); }},
	{"bridgemain.h/GuiGetMainThreadId",   [] { GuiGetMainThreadId(); }},
	{"bridgemain.h/GuiSetDebuggeeNotes",   [] { GuiSetDebuggeeNotes(); }},
	{"_scriptapi_debug.h/StepOver",   [] { Script::Debug::StepOver(); }},
	{"_scriptapi_register.h/SetRBX",   [] { Script::Register::SetRBX(); }},
	{"bridgegraph.h/AddNode",   [] { ::BridgeCFGraph::AddNode(); }},
	{"_scriptapi_module.h/GetMainModuleName",   [] { Script::Module::GetMainModuleName(); }},
	{"_scriptapi_module.h/SectionListFromName",   [] { Script::Module::SectionListFromName(); }},
	{"bridgemain.h/GuiReferenceInitialize",   [] { GuiReferenceInitialize(); }},
	{"bridgemain.h/GuiAutoCompleteClearAll",   [] { GuiAutoCompleteClearAll(); }},
	{"bridgemain.h/GuiUpdateTraceBrowser",   [] { GuiUpdateTraceBrowser(); }},
	{"_scriptapi_module.h/BaseFromAddr",   [] { Script::Module::BaseFromAddr(); }},
	{"_scriptapi_register.h/SetCSI",   [] { Script::Register::SetCSI(); }},
	{"_scriptapi_register.h/SetR14",   [] { Script::Register::SetR14(); }},
	{"bridgemain.h/DbgDelEncodeTypeSegment",   [] { DbgDelEncodeTypeSegment(); }},
	{"bridgemain.h/DbgClearBookmarkRange",   [] { DbgClearBookmarkRange(); }},
	{"_scriptapi_stack.h/Pop",   [] { Script::Stack::Pop(); }},
	{"_scriptapi_bookmark.h/Set",   [] { Script::Bookmark::Set(); }},
	{"_scriptapi_register.h/GetSP",   [] { Script::Register::GetSP(); }},
	{"bridgemain.h/DbgScriptLoad",   [] { DbgScriptLoad(); }},
	{"bridgemain.h/DbgArgumentDel",   [] { DbgArgumentDel(); }},
	{"bridgemain.h/DbgSymbolEnumFromCache",   [] { DbgSymbolEnumFromCache(); }},
	{"_scriptapi_memory.h/ReadByte",   [] { Script::Memory::ReadByte(); }},
	{"_scriptapi_flag.h/SetAF",   [] { Script::Flag::SetAF(); }},
	{"_scriptapi_register.h/SetR15",   [] { Script::Register::SetR15(); }},
	{"_scriptapi_register.h/SetR8B",   [] { Script::Register::SetR8B(); }},
	{"_scriptapi_register.h/GetESP",   [] { Script::Register::GetESP(); }},
	{"_scriptapi_comment.h/Set",   [] { Script::Comment::Set(); }},
	{"_scriptapi_gui.h/CloseQWidgetTab",   [] { Script::Gui::CloseQWidgetTab(); }},
	{"bridgemain.h/GuiLogClear",   [] { GuiLogClear(); }},
	{"_scriptapi_register.h/GetDX",   [] { Script::Register::GetDX(); }},
	{"bridgemain.h/DbgMenuEntryClicked",   [] { DbgMenuEntryClicked(); }},
	{"_scriptapi_register.h/SetR9B",   [] { Script::Register::SetR9B(); }},
	{"_scriptapi_flag.h/GetPF",   [] { Script::Flag::GetPF(); }},
	{"_scriptapi_flag.h/GetAF",   [] { Script::Flag::GetAF(); }},
	{"_scriptapi_register.h/SetR10D",   [] { Script::Register::SetR10D(); }},
	{"bridgemain.h/DbgSetAutoFunctionAt",   [] { DbgSetAutoFunctionAt(); }},
	{"_scriptapi_module.h/EntryFromAddr",   [] { Script::Module::EntryFromAddr(); }},
	{"bridgemain.h/DbgGetDebugEngine",   [] { DbgGetDebugEngine(); }},
	{"_scriptapi_register.h/GetR11W",   [] { Script::Register::GetR11W(); }},
	{"bridgemain.h/GuiUpdateSEHChain",   [] { GuiUpdateSEHChain(); }},
	{"_scriptapi_register.h/SetCCX",   [] { Script::Register::SetCCX(); }},
	{"_scriptapi_flag.h/GetDF",   [] { Script::Flag::GetDF(); }},
	{"_scriptapi_register.h/SetRAX",   [] { Script::Register::SetRAX(); }},
	{"bridgemain.h/DbgValFromString",   [] { DbgValFromString(); }},
	{"_scriptapi_flag.h/SetZF",   [] { Script::Flag::SetZF(); }},
	{"_scriptapi_flag.h/Get",   [] { Script::Flag::Get(); }},
	{"_scriptapi_function.h/DeleteRange",   [] { Script::Function::DeleteRange(); }},
	{"bridgemain.h/BridgeSettingFlush",   [] { BridgeSettingFlush(); }},
	{"_scriptapi_module.h/GetMainModuleEntry",   [] { Script::Module::GetMainModuleEntry(); }},
	{"bridgemain.h/DbgGetWatchList",   [] { DbgGetWatchList(); }},
	{"_scriptapi_register.h/GetR9W",   [] { Script::Register::GetR9W(); }},
	{"bridgemain.h/GuiSymbolLogClear",   [] { GuiSymbolLogClear(); }},
	{"_scriptapi_comment.h/DeleteRange",   [] { Script::Comment::DeleteRange(); }},
	{"bridgemain.h/GuiAddQWidgetTab",   [] { GuiAddQWidgetTab(); }},
	{"bridgemain.h/GuiSetLastException",   [] { GuiSetLastException(); }},
	{"bridgemain.h/DbgFunctionDel",   [] { DbgFunctionDel(); }},
	{"bridgemain.h/BridgeSettingSetUint",   [] { BridgeSettingSetUint(); }},
	{"bridgemain.h/DbgSetLabelAt",   [] { DbgSetLabelAt(); }},
	{"_scriptapi_label.h/Get",   [] { Script::Label::Get(); }},
	{"bridgemain.h/DbgScriptStep",   [] { DbgScriptStep(); }},
	{"bridgemain.h/GuiGetLineWindow",   [] { GuiGetLineWindow(); }},
	{"bridgemain.h/BridgeFree",   [] { BridgeFree(); }},
	{"_scriptapi_register.h/SetR14D",   [] { Script::Register::SetR14D(); }},
	{"_scriptapi_register.h/GetDR2",   [] { Script::Register::GetDR2(); }},
	{"_scriptapi_register.h/SetDR7",   [] { Script::Register::SetDR7(); }},
	{"bridgemain.h/DbgSymbolEnumRange",   [] { DbgSymbolEnumRange(); }},
	{"bridgemain.h/DbgFunctionOverlaps",   [] { DbgFunctionOverlaps(); }},
	{"_scriptapi_memory.h/Write",   [] { Script::Memory::Write(); }},
	{"bridgemain.h/BridgeIsARM64Emulated",   [] { BridgeIsARM64Emulated(); }},
	{"bridgemain.h/DbgScriptBpToggle",   [] { DbgScriptBpToggle(); }},
	{"_scriptapi_debug.h/Wait",   [] { Script::Debug::Wait(); }},
	{"_scriptapi_comment.h/Delete",   [] { Script::Comment::Delete(); }},
	{"_scriptapi_register.h/GetR10D",   [] { Script::Register::GetR10D(); }},
	{"_scriptapi_label.h/DeleteRange",   [] { Script::Label::DeleteRange(); }},
	{"_scriptapi_register.h/GetR10B",   [] { Script::Register::GetR10B(); }},
	{"bridgemain.h/GuiSymbolLogAdd",   [] { GuiSymbolLogAdd(); }},
	{"bridgemain.h/GuiShowCpu",   [] { GuiShowCpu(); }},
	{"bridgemain.h/DbgScriptGetBranchInfo",   [] { DbgScriptGetBranchInfo(); }},
	{"_scriptapi_debug.h/DeleteHardwareBreakpoint",   [] { Script::Debug::DeleteHardwareBreakpoint(); }},
	{"bridgemain.h/GuiAddStatusBarMessage",   [] { GuiAddStatusBarMessage(); }},
	{"bridgemain.h/GuiDisableLog",   [] { GuiDisableLog(); }},
	{"bridgemain.h/GuiGetCurrentGraph",   [] { GuiGetCurrentGraph(); }},
	{"bridgemain.h/GuiShowQWidgetTab",   [] { GuiShowQWidgetTab(); }},
	{"bridgemain.h/GuiStackDumpAt",   [] { GuiStackDumpAt(); }},
	{"_scriptapi_register.h/SetR11",   [] { Script::Register::SetR11(); }},
	{"_scriptapi_register.h/SetBP",   [] { Script::Register::SetBP(); }},
	{"_scriptapi_register.h/SetR13",   [] { Script::Register::SetR13(); }},
	{"_scriptapi_register.h/SetBH",   [] { Script::Register::SetBH(); }},
	{"_scriptapi_register.h/SetAH",   [] { Script::Register::SetAH(); }},
	{"bridgemain.h/GuiLogRedirectStop",   [] { GuiLogRedirectStop(); }},
	{"bridgemain.h/GuiMenuAdd",   [] { GuiMenuAdd(); }},
	{"bridgemain.h/GuiLoadSourceFileEx",   [] { GuiLoadSourceFileEx(); }},
	{"_scriptapi_argument.h/Overlaps",   [] { Script::Argument::Overlaps(); }},
	{"_scriptapi_memory.h/ReadDword",   [] { Script::Memory::ReadDword(); }},
	{"_scriptapi_bookmark.h/Get",   [] { Script::Bookmark::Get(); }},
	{"_scriptapi_memory.h/RemoteAlloc",   [] { Script::Memory::RemoteAlloc(); }},
	{"bridgemain.h/GuiMenuAddEntry",   [] { GuiMenuAddEntry(); }},
	{"bridgemain.h/BridgeSettingRead",   [] { BridgeSettingRead(); }},
	{"bridgemain.h/GuiScriptSetTitle",   [] { GuiScriptSetTitle(); }},
	{"bridgemain.h/GuiOpenTraceFile",   [] { GuiOpenTraceFile(); }},
	{"bridgemain.h/DbgGetBranchDestination",   [] { DbgGetBranchDestination(); }},
	{"bridgemain.h/GuiScriptClear",   [] { GuiScriptClear(); }},
	{"_scriptapi_flag.h/GetSF",   [] { Script::Flag::GetSF(); }},
	{"_scriptapi_register.h/GetESI",   [] { Script::Register::GetESI(); }},
	{"_scriptapi_module.h/BaseFromName",   [] { Script::Module::BaseFromName(); }},
	{"bridgemain.h/GuiGetGlobalNotes",   [] { GuiGetGlobalNotes(); }},
	{"_scriptapi_register.h/SetR8W",   [] { Script::Register::SetR8W(); }},
	{"bridgemain.h/GuiUpdateWindowTitle",   [] { GuiUpdateWindowTitle(); }},
	{"_scriptapi_module.h/GetMainModuleInfo",   [] { Script::Module::GetMainModuleInfo(); }},
	{"_scriptapi_comment.h/Clear",   [] { Script::Comment::Clear(); }},
	{"_scriptapi_register.h/SetDR6",   [] { Script::Register::SetDR6(); }},
	{"_scriptapi_pattern.h/SearchAndReplaceMem",   [] { Script::Pattern::SearchAndReplaceMem(); }},
	{"_scriptapi_register.h/SetBPL",   [] { Script::Register::SetBPL(); }},
	{"_scriptapi_flag.h/Set",   [] { Script::Flag::Set(); }},
	{"_scriptapi_register.h/GetCDI",   [] { Script::Register::GetCDI(); }},
	{"bridgemain.h/GuiScriptSetIp",   [] { GuiScriptSetIp(); }},
	{"_scriptapi_debug.h/Run",   [] { Script::Debug::Run(); }},
	{"_scriptapi_module.h/PathFromName",   [] { Script::Module::PathFromName(); }},
	{"bridgemain.h/DbgReleaseEncodeTypeBuffer",   [] { DbgReleaseEncodeTypeBuffer(); }},
	{"_scriptapi_memory.h/WriteWord",   [] { Script::Memory::WriteWord(); }},
	{"bridgemain.h/DbgGetTimeWastedCounter",   [] { DbgGetTimeWastedCounter(); }},
	{"_scriptapi_bookmark.h/GetList",   [] { Script::Bookmark::GetList(); }},
	{"_scriptapi_register.h/GetSPL",   [] { Script::Register::GetSPL(); }},
	{"_scriptapi_register.h/SetBL",   [] { Script::Register::SetBL(); }},
	{"bridgemain.h/DbgMemGetPageSize",   [] { DbgMemGetPageSize(); }},
	{"bridgemain.h/DbgGetPebAddress",   [] { DbgGetPebAddress(); }},
	{"_scriptapi_flag.h/GetIF",   [] { Script::Flag::GetIF(); }},
	{"_scriptapi_debug.h/StepIn",   [] { Script::Debug::StepIn(); }},
	{"_scriptapi_register.h/SetRIP",   [] { Script::Register::SetRIP(); }},
	{"_scriptapi_register.h/GetR12D",   [] { Script::Register::GetR12D(); }},
	{"_scriptapi_comment.h/Get",   [] { Script::Comment::Get(); }},
	{"_scriptapi_register.h/GetDL",   [] { Script::Register::GetDL(); }},
	{"_scriptapi_flag.h/SetDF",   [] { Script::Flag::SetDF(); }},
	{"bridgemain.h/GuiGotoTrace",   [] { GuiGotoTrace(); }},
	{"bridgemain.h/GuiFocusView",   [] { GuiFocusView(); }},
	{"_scriptapi_function.h/Delete",   [] { Script::Function::Delete(); }},
	{"bridgemain.h/GuiUpdatePatches",   [] { GuiUpdatePatches(); }},
	{"bridgemain.h/DbgClearAutoCommentRange",   [] { DbgClearAutoCommentRange(); }},
	{"_scriptapi_register.h/Size",   [] { Script::Register::Size(); }},
	{"bridgemain.h/DbgWinEventGlobal",   [] { DbgWinEventGlobal(); }},
	{"bridgemain.h/GuiUpdateRegisterView",   [] { GuiUpdateRegisterView(); }},
	{"bridgemain.h/DbgExit",   [] { DbgExit(); }},
	{"bridgemain.h/DbgGetCommentAt",   [] { DbgGetCommentAt(); }},
	{"_scriptapi_memory.h/IsValidPtr",   [] { Script::Memory::IsValidPtr(); }},
	{"_scriptapi_register.h/GetRSP",   [] { Script::Register::GetRSP(); }},
	{"bridgemain.h/DbgFunctionAdd",   [] { DbgFunctionAdd(); }},
	{"bridgemain.h/DbgGetProcessId",   [] { DbgGetProcessId(); }},
	{"_scriptapi_register.h/GetR8D",   [] { Script::Register::GetR8D(); }},
	{"_scriptapi_register.h/GetCFLAGS",   [] { Script::Register::GetCFLAGS(); }},
	{"_scriptapi_memory.h/ReadPtr",   [] { Script::Memory::ReadPtr(); }},
	{"_scriptapi_module.h/InfoFromName",   [] { Script::Module::InfoFromName(); }},
	{"_scriptapi_register.h/SetR15B",   [] { Script::Register::SetR15B(); }},
	{"bridgemain.h/DbgMemIsValidReadPtr",   [] { DbgMemIsValidReadPtr(); }},
	{"_scriptapi_register.h/GetBL",   [] { Script::Register::GetBL(); }},
	{"_scriptapi_module.h/SectionFromName",   [] { Script::Module::SectionFromName(); }},
	{"bridgemain.h/GuiAddInfoLine",   [] { GuiAddInfoLine(); }},
	{"_scriptapi_register.h/GetBH",   [] { Script::Register::GetBH(); }},
	{"bridgemain.h/DbgGetSymbolInfoAt",   [] { DbgGetSymbolInfoAt(); }},
	{"_scriptapi_register.h/GetR9",   [] { Script::Register::GetR9(); }},
	{"_scriptapi_register.h/GetR12W",   [] { Script::Register::GetR12W(); }},
	{"_scriptapi_module.h/SizeFromName",   [] { Script::Module::SizeFromName(); }},
	{"_scriptapi_module.h/PathFromAddr",   [] { Script::Module::PathFromAddr(); }},
	{"_scriptapi_pattern.h/WriteMem",   [] { Script::Pattern::WriteMem(); }},
	{"_scriptapi_register.h/SetR9D",   [] { Script::Register::SetR9D(); }},
	{"_scriptapi_register.h/GetEIP",   [] { Script::Register::GetEIP(); }},
	{"bridgemain.h/GuiMenuSetEntryIcon",   [] { GuiMenuSetEntryIcon(); }},
	{"_scriptapi_module.h/GetImports",   [] { Script::Module::GetImports(); }},
	{"_scriptapi_register.h/GetCAX",   [] { Script::Register::GetCAX(); }},
	{"_scriptapi_register.h/SetR14B",   [] { Script::Register::SetR14B(); }},
	{"_scriptapi_register.h/GetDR1",   [] { Script::Register::GetDR1(); }},
	{"_scriptapi_register.h/GetRCX",   [] { Script::Register::GetRCX(); }},
	{"bridgemain.h/GuiReferenceSetSearchStartCol",   [] { GuiReferenceSetSearchStartCol(); }},
	{"bridgemain.h/DbgGetRegDumpEx",   [] { DbgGetRegDumpEx(); }},
	{"_scriptapi_module.h/GetMainModuleBase",   [] { Script::Module::GetMainModuleBase(); }},
	{"_scriptapi_register.h/SetEBX",   [] { Script::Register::SetEBX(); }},
	{"bridgemain.h/DbgCmdExecDirect",   [] { DbgCmdExecDirect(); }},
	{"_scriptapi_register.h/SetCFLAGS",   [] { Script::Register::SetCFLAGS(); }},
	{"_scriptapi_register.h/GetDR6",   [] { Script::Register::GetDR6(); }},
	{"bridgemain.h/DbgDisasmAt",   [] { DbgDisasmAt(); }},
	{"bridgemain.h/GuiCloseQWidgetTab",   [] { GuiCloseQWidgetTab(); }},
	{"_scriptapi_gui.h/ShowQWidgetTab",   [] { Script::Gui::ShowQWidgetTab(); }},
	{"bridgemain.h/DbgGetModuleAt",   [] { DbgGetModuleAt(); }},
	{"_scriptapi_register.h/SetDIL",   [] { Script::Register::SetDIL(); }},
	{"bridgemain.h/DbgClearLabelRange",   [] { DbgClearLabelRange(); }},
	{"bridgemain.h/DbgMenuPrepare",   [] { DbgMenuPrepare(); }},
	{"bridgemain.h/GuiScriptMessage",   [] { GuiScriptMessage(); }},
	{"_scriptapi_flag.h/SetTF",   [] { Script::Flag::SetTF(); }},
	{"_scriptapi_argument.h/Clear",   [] { Script::Argument::Clear(); }},
	{"bridgemain.h/GuiReferenceSearchGetCellContent",   [] { GuiReferenceSearchGetCellContent(); }},
	{"_scriptapi_register.h/SetSIL",   [] { Script::Register::SetSIL(); }},
	{"bridgemain.h/GuiUpdateBreakpointsView",   [] { GuiUpdateBreakpointsView(); }},
	{"_scriptapi_register.h/SetR14W",   [] { Script::Register::SetR14W(); }},
	{"_scriptapi_function.h/Clear",   [] { Script::Function::Clear(); }},
	{"bridgemain.h/DbgArgumentOverlaps",   [] { DbgArgumentOverlaps(); }},
	{"_scriptapi_register.h/GetRIP",   [] { Script::Register::GetRIP(); }},
	{"bridgemain.h/GuiReferenceReloadData",   [] { GuiReferenceReloadData(); }},
	{"bridgemain.h/BridgeStart",   [] { BridgeStart(); }},
	{"_scriptapi_register.h/SetR8D",   [] { Script::Register::SetR8D(); }},
	{"bridgemain.h/DbgGetXrefCountAt",   [] { DbgGetXrefCountAt(); }},
	{"bridgemain.h/GuiUpdateAllViews",   [] { GuiUpdateAllViews(); }},
	{"_scriptapi_flag.h/SetIF",   [] { Script::Flag::SetIF(); }},
	{"_scriptapi_memory.h/Read",   [] { Script::Memory::Read(); }},
	{"bridgemain.h/GuiDisplayWarning",   [] { GuiDisplayWarning(); }},
	{"bridgemain.h/GuiUpdateMemoryView",   [] { GuiUpdateMemoryView(); }},
	{"_scriptapi_register.h/GetBPL",   [] { Script::Register::GetBPL(); }},
	{"_scriptapi_register.h/GetR8B",   [] { Script::Register::GetR8B(); }},
	{"bridgemain.h/GuiTypeClear",   [] { GuiTypeClear(); }},
	{"_scriptapi_register.h/GetCBX",   [] { Script::Register::GetCBX(); }},
	{"_scriptapi_flag.h/GetTF",   [] { Script::Flag::GetTF(); }},
	{"bridgemain.h/GuiExecuteOnGuiThread",   [] { GuiExecuteOnGuiThread(); }},
	{"bridgemain.h/DbgGetThreadHandle",   [] { DbgGetThreadHandle(); }},
	{"_scriptapi_register.h/SetR12",   [] { Script::Register::SetR12(); }},
	{"_scriptapi_label.h/IsTemporary",   [] { Script::Label::IsTemporary(); }},
	{"_scriptapi_register.h/GetCX",   [] { Script::Register::GetCX(); }},
	{"bridgegraph.h/ToGraphList",   [] { ::BridgeCFGraph::ToGraphList(); }},
	{"bridgegraph.h/AddParent",   [] { ::BridgeCFGraph::AddParent(); }},
	{"_scriptapi_register.h/GetEDX",   [] { Script::Register::GetEDX(); }},
	{"bridgemain.h/DbgClearCommentRange",   [] { DbgClearCommentRange(); }},
	{"bridgemain.h/DbgClearAutoFunctionRange",   [] { DbgClearAutoFunctionRange(); }},
	{"_scriptapi_register.h/GetR11D",   [] { Script::Register::GetR11D(); }},
	{"bridgemain.h/DbgScriptRun",   [] { DbgScriptRun(); }},
	{"bridgemain.h/DbgSetAutoBookmarkAt",   [] { DbgSetAutoBookmarkAt(); }},
	{"bridgemain.h/GuiReferenceSetCellContent",   [] { GuiReferenceSetCellContent(); }},
	{"_scriptapi_register.h/GetR9D",   [] { Script::Register::GetR9D(); }},
	{"bridgemain.h/GuiShowThreads",   [] { GuiShowThreads(); }},
	{"_scriptapi_register.h/SetSPL",   [] { Script::Register::SetSPL(); }},
	{"_scriptapi_register.h/SetDR2",   [] { Script::Register::SetDR2(); }},
	{"bridgemain.h/DbgValToString",   [] { DbgValToString(); }},
	{"_scriptapi_register.h/GetCL",   [] { Script::Register::GetCL(); }},
	{"_scriptapi_pattern.h/FindMem",   [] { Script::Pattern::FindMem(); }},
	{"_scriptapi_misc.h/Free",   [] { Script::Misc::Free(); }},
	{"_scriptapi_argument.h/GetInfo",   [] { Script::Argument::GetInfo(); }},
	{"bridgemain.h/GuiLogSave",   [] { GuiLogSave(); }},
	{"bridgemain.h/DbgCmdExec",   [] { DbgCmdExec(); }},
	{"bridgemain.h/GuiSetDebugStateFast",   [] { GuiSetDebugStateFast(); }},
	{"_scriptapi_memory.h/WriteQword",   [] { Script::Memory::WriteQword(); }},
	{"_scriptapi_register.h/GetR11",   [] { Script::Register::GetR11(); }},
	{"_scriptapi_gui.h/SelectionGetStart",   [] { Script::Gui::SelectionGetStart(); }},
	{"_scriptapi_register.h/SetDX",   [] { Script::Register::SetDX(); }},
	{"bridgemain.h/DbgGetStringAt",   [] { DbgGetStringAt(); }},
	{"_scriptapi_flag.h/SetPF",   [] { Script::Flag::SetPF(); }},
	{"bridgemain.h/BridgeIsProcessElevated",   [] { BridgeIsProcessElevated(); }},
	{"bridgemain.h/DbgScriptCmdExec",   [] { DbgScriptCmdExec(); }},
	{"_scriptapi_memory.h/GetProtect",   [] { Script::Memory::GetProtect(); }},
	{"_scriptapi_argument.h/Delete",   [] { Script::Argument::Delete(); }},
	{"_scriptapi_register.h/GetRAX",   [] { Script::Register::GetRAX(); }},
	{"_scriptapi_register.h/SetR12B",   [] { Script::Register::SetR12B(); }},
	{"_scriptapi_register.h/GetR14",   [] { Script::Register::GetR14(); }},
	{"_scriptapi_label.h/Delete",   [] { Script::Label::Delete(); }},
	{"bridgemain.h/GuiUpdateTypeWidget",   [] { GuiUpdateTypeWidget(); }},
	{"_scriptapi_misc.h/Alloc",   [] { Script::Misc::Alloc(); }},
	{"_scriptapi_module.h/GetMainModuleSectionList",   [] { Script::Module::GetMainModuleSectionList(); }},
	{"bridgemain.h/GuiUpdateDisassemblyView",   [] { GuiUpdateDisassemblyView(); }},
	{"bridgemain.h/GuiSelectInMemoryMap",   [] { GuiSelectInMemoryMap(); }},
	{"_scriptapi_pattern.h/SearchAndReplace",   [] { Script::Pattern::SearchAndReplace(); }},
	{"bridgemain.h/DbgMemWrite",   [] { DbgMemWrite(); }},
	{"_scriptapi_flag.h/GetCF",   [] { Script::Flag::GetCF(); }},
	{"bridgemain.h/GuiReferenceAddColumn",   [] { GuiReferenceAddColumn(); }},
	{"bridgemain.h/DbgGetXrefTypeAt",   [] { DbgGetXrefTypeAt(); }},
	{"_scriptapi_gui.h/SelectionSet",   [] { Script::Gui::SelectionSet(); }},
	{"_scriptapi_function.h/Overlaps",   [] { Script::Function::Overlaps(); }},
	{"_scriptapi_register.h/GetR12B",   [] { Script::Register::GetR12B(); }},
	{"_scriptapi_module.h/SectionCountFromAddr",   [] { Script::Module::SectionCountFromAddr(); }},
	{"_scriptapi_register.h/GetR12",   [] { Script::Register::GetR12(); }},
	{"bridgemain.h/GuiAutoCompleteDelCmd",   [] { GuiAutoCompleteDelCmd(); }},
	{"_scriptapi_register.h/SetR10B",   [] { Script::Register::SetR10B(); }},
	{"bridgemain.h/GuiAutoCompleteAddCmd",   [] { GuiAutoCompleteAddCmd(); }},
	{"_scriptapi_pattern.h/Find",   [] { Script::Pattern::Find(); }},
	{"bridgemain.h/GuiProcessEvents",   [] { GuiProcessEvents(); }},
	{"bridgemain.h/DbgGetEncodeSizeAt",   [] { DbgGetEncodeSizeAt(); }},
	{"bridgemain.h/DbgSymbolEnum",   [] { DbgSymbolEnum(); }},
	{"_scriptapi_label.h/FromString",   [] { Script::Label::FromString(); }},
	{"bridgemain.h/GuiMenuSetIcon",   [] { GuiMenuSetIcon(); }},
	{"_scriptapi_register.h/GetDR0",   [] { Script::Register::GetDR0(); }},
	{"bridgemain.h/DbgSetAutoCommentAt",   [] { DbgSetAutoCommentAt(); }},
	{"bridgemain.h/DbgGetSymbolInfo",   [] { DbgGetSymbolInfo(); }},
	{"_scriptapi_debug.h/SetBreakpoint",   [] { Script::Debug::SetBreakpoint(); }},
	{"bridgemain.h/GuiUnregisterScriptLanguage",   [] { GuiUnregisterScriptLanguage(); }},
	{"_scriptapi_bookmark.h/Clear",   [] { Script::Bookmark::Clear(); }},
	{"bridgemain.h/GuiReferenceDeleteAllColumns",   [] { GuiReferenceDeleteAllColumns(); }},
	{"bridgemain.h/GuiAddFavouriteCommand",   [] { GuiAddFavouriteCommand(); }},
	{"_scriptapi_register.h/GetCDX",   [] { Script::Register::GetCDX(); }},
	{"_scriptapi_register.h/GetRDX",   [] { Script::Register::GetRDX(); }},
	{"_scriptapi_register.h/SetR10",   [] { Script::Register::SetR10(); }},
	{"_scriptapi_register.h/GetR13B",   [] { Script::Register::GetR13B(); }},
	{"bridgemain.h/DbgLoopDel",   [] { DbgLoopDel(); }},
	{"bridgemain.h/DbgModBaseFromName",   [] { DbgModBaseFromName(); }},
	{"bridgemain.h/DbgXrefGet",   [] { DbgXrefGet(); }},
	{"_scriptapi_label.h/Set",   [] { Script::Label::Set(); }},
	{"_scriptapi_register.h/SetR9",   [] { Script::Register::SetR9(); }},
	{"bridgemain.h/GuiSymbolUpdateModuleList",   [] { GuiSymbolUpdateModuleList(); }},
	{"bridgemain.h/DbgDisasmFastAt",   [] { DbgDisasmFastAt(); }},
	{"_scriptapi_gui.h/MessageYesNo",   [] { Script::Gui::MessageYesNo(); }},
	{"_scriptapi_register.h/GetAH",   [] { Script::Register::GetAH(); }},
	{"_scriptapi_register.h/SetR11B",   [] { Script::Register::SetR11B(); }},
	{"_scriptapi_register.h/GetR9B",   [] { Script::Register::GetR9B(); }},
	{"_scriptapi_module.h/GetExports",   [] { Script::Module::GetExports(); }},
	{"bridgemain.h/GuiLogRedirect",   [] { GuiLogRedirect(); }},
	{"bridgemain.h/DbgGetTebAddress",   [] { DbgGetTebAddress(); }},
	{"bridgemain.h/GuiSymbolSetProgress",   [] { GuiSymbolSetProgress(); }},
	{"_scriptapi_gui.h/InputValue",   [] { Script::Gui::InputValue(); }},
	{"bridgemain.h/GuiUpdateTimeWastedCounter",   [] { GuiUpdateTimeWastedCounter(); }},
	{"_scriptapi_debug.h/StepOut",   [] { Script::Debug::StepOut(); }},
	{"_scriptapi_register.h/GetR14D",   [] { Script::Register::GetR14D(); }},
	{"_scriptapi_register.h/GetR15",   [] { Script::Register::GetR15(); }},
	{"bridgemain.h/GuiReferenceSearchGetRowCount",   [] { GuiReferenceSearchGetRowCount(); }},
	{"bridgemain.h/DbgSettingsUpdated",   [] { DbgSettingsUpdated(); }},
	{"_scriptapi_register.h/SetR9W",   [] { Script::Register::SetR9W(); }},
	{"_scriptapi_module.h/GetMainModuleSectionCount",   [] { Script::Module::GetMainModuleSectionCount(); }},
	{"_scriptapi_module.h/InfoFromAddr",   [] { Script::Module::InfoFromAddr(); }},
	{"bridgemain.h/GuiMenuRemove",   [] { GuiMenuRemove(); }},
	{"_scriptapi_memory.h/GetSize",   [] { Script::Memory::GetSize(); }},
	{"_scriptapi_register.h/GetCSI",   [] { Script::Register::GetCSI(); }},
	{"bridgemain.h/DbgStackCommentGet",   [] { DbgStackCommentGet(); }},
	{"bridgemain.h/GuiReferenceSetProgress",   [] { GuiReferenceSetProgress(); }},
	{"_scriptapi_register.h/GetDR3",   [] { Script::Register::GetDR3(); }},
	{"_scriptapi_module.h/SectionFromAddr",   [] { Script::Module::SectionFromAddr(); }},
	{"_scriptapi_register.h/SetESI",   [] { Script::Register::SetESI(); }},
	{"bridgemain.h/DbgMemFindBaseAddr",   [] { DbgMemFindBaseAddr(); }},
	{"_scriptapi_register.h/GetDI",   [] { Script::Register::GetDI(); }},
	{"bridgemain.h/GuiSetFavouriteToolShortcut",   [] { GuiSetFavouriteToolShortcut(); }},
	{"bridgemain.h/GuiGetDisassembly",   [] { GuiGetDisassembly(); }},
	{"_scriptapi_register.h/GetEBX",   [] { Script::Register::GetEBX(); }},
	{"_scriptapi_flag.h/GetOF",   [] { Script::Flag::GetOF(); }},
	{"bridgemain.h/GuiFlushLog",   [] { GuiFlushLog(); }},
	{"_scriptapi_register.h/GetEAX",   [] { Script::Register::GetEAX(); }},
	{"bridgemain.h/GuiUpdateDisable",   [] { GuiUpdateDisable(); }},
	{"_scriptapi_register.h/SetRSP",   [] { Script::Register::SetRSP(); }},
	{"bridgemain.h/DbgSetAutoLabelAt",   [] { DbgSetAutoLabelAt(); }},
	{"_scriptapi_register.h/SetDL",   [] { Script::Register::SetDL(); }},
	{"_scriptapi_register.h/SetR15D",   [] { Script::Register::SetR15D(); }},
	{"_scriptapi_memory.h/SetProtect",   [] { Script::Memory::SetProtect(); }},
	{"bridgemain.h/DbgInit",   [] { DbgInit(); }},
	{"_scriptapi_misc.h/ParseExpression",   [] { Script::Misc::ParseExpression(); }},
	{"_scriptapi_register.h/GetR15B",   [] { Script::Register::GetR15B(); }},
	{"_scriptapi_register.h/SetCDI",   [] { Script::Register::SetCDI(); }},
	{"_scriptapi_register.h/SetEIP",   [] { Script::Register::SetEIP(); }},
	{"_scriptapi_memory.h/ReadWord",   [] { Script::Memory::ReadWord(); }},
	{"_scriptapi_register.h/SetR13B",   [] { Script::Register::SetR13B(); }},
	{"_scriptapi_register.h/SetSI",   [] { Script::Register::SetSI(); }},
	{"bridgemain.h/GuiShowTrace",   [] { GuiShowTrace(); }},
	{"_scriptapi_register.h/SetRDX",   [] { Script::Register::SetRDX(); }},
};
    if (auto it = handlers.find(path); it != handlers.end()) it->second();//todo: 这里的路径解析有问题，发包恢复客户端
}


/*
void echo(const std::string path) {
    // 使用 std::map 来存储路径和对应的操作函数
    std::map<std::string, std::function<void()>> pathActions = {
            {"_scriptapi_argument.h/Add",   []() {
                Script::Argument::Add(nullptr);
            }},
            {"_scriptapi_argument.h/Clear", []() {
                Script::Argument::Clear();
            }},
    };

    // 查找并执行对应的操作
    auto it = pathActions.find(path);
    if (it != pathActions.end()) {
        it->second();
    } else {
        // 默认情况下什么都不做
    }
}


#include <iostream>
#include <string>

// 编译期哈希计算（DJB2算法）
constexpr size_t hash(const char *str) noexcept {
    size_t hash = 5381;
    while (*str != '\0') {
        hash = ((hash << 5) + hash) + *str; // hash = hash * 33 + c
        ++str;
    }
    return hash;
}

void dispatch2(const std::string &path) {
    const size_t h = hash(path.c_str());
    switch (h) {
        case hash("Namespace1::myFunc"):
            if (path != "Namespace1::myFunc") break; // 防哈希碰撞
            std::cout << "Call Namespace1::myFunc\n";
            break;
        case hash("Namespace2::myFunc"):
            if (path != "Namespace2::myFunc") break;
            std::cout << "Call Namespace2::myFunc\n";
            break;
        default:
            std::cerr << "Unknown path: " << path << "\n";
    }
}

int main() {
    dispatch("Namespace1::myFunc");
    dispatch("Namespace2::myFunc");
    dispatch("InvalidPath");
    return 0;
}
 */

#endif //MCPX64DBG_ECHO_GEN_H
