// Code generated by yy. DO NOT EDIT.

// Copyright 2022 The CC Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package cc

import (
	"fmt"
)

func ExampleAbstractDeclarator_ptr() {
	fmt.Println(exampleAST(200, "void f(int*);"))
	// Output:
}

func ExampleAbstractDeclarator_decl() {
	fmt.Println(exampleAST(201, "void f(int());"))
	// Output:
}

func ExampleAdditiveExpression_add() {
	fmt.Println(exampleAST(49, "int i = x+y;"))
	// Output:
}

func ExampleAdditiveExpression_sub() {
	fmt.Println(exampleAST(50, "int i = x-y;"))
	// Output:
}

func ExampleAlignmentSpecifier_type() {
	fmt.Println(exampleAST(176, "_Alignas(double) char c;"))
	// Output:
}

func ExampleAlignmentSpecifier_expr() {
	fmt.Println(exampleAST(177, "_Alignas(0ll) char c;"))
	// Output:
}

func ExampleAndExpression_and() {
	fmt.Println(exampleAST(63, "int i = x & y;"))
	// Output:
}

func ExampleArgumentExpressionList_case0() {
	fmt.Println(exampleAST(24, "int i = f(x);"))
	// Output:
}

func ExampleArgumentExpressionList_case1() {
	fmt.Println(exampleAST(25, "int i = f(x, y);"))
	// Output:
}

func ExampleAsm_case0() {
	fmt.Println(exampleAST(265, "__asm__(\"nop\");"))
	// Output:
}

func ExampleAsmArgList_case0() {
	fmt.Println(exampleAST(263, "__asm__(\"nop\": a);"))
	// Output:
}

func ExampleAsmArgList_case1() {
	fmt.Println(exampleAST(264, "__asm__(\"nop\": a : b);"))
	// Output:
}

func ExampleAsmExpressionList_case0() {
	fmt.Println(exampleAST(261, "__asm__(\"nop\": a);"))
	// Output:
}

func ExampleAsmExpressionList_case1() {
	fmt.Println(exampleAST(262, "__asm__(\"nop\": a, b);"))
	// Output:
}

func ExampleAsmIndex_case0() {
	fmt.Println(exampleAST(260, "__asm__(\"nop\": [a] b);"))
	// Output:
}

func ExampleAsmQualifier_volatile() {
	fmt.Println(exampleAST(267, "__asm__ volatile (\"nop\");"))
	// Output:
}

func ExampleAsmQualifier_inline() {
	fmt.Println(exampleAST(268, "__asm__ inline (\"nop\");"))
	// Output:
}

func ExampleAsmQualifier_goto() {
	fmt.Println(exampleAST(269, "__asm__ goto (\"nop\");"))
	// Output:
}

func ExampleAsmQualifierList_case0() {
	fmt.Println(exampleAST(270, "__asm__ inline (\"nop\");"))
	// Output:
}

func ExampleAsmQualifierList_case1() {
	fmt.Println(exampleAST(271, "__asm__ inline volatile (\"nop\");"))
	// Output:
}

func ExampleAsmStatement_case0() {
	fmt.Println(exampleAST(266, "void f() { __asm__(\"nop\"); }"))
	// Output:
}

func ExampleAssignmentExpression_assign() {
	fmt.Println(exampleAST(75, "int f() { x = y; }"))
	// Output:
}

func ExampleAssignmentExpression_mul() {
	fmt.Println(exampleAST(76, "int f() { x *= y; }"))
	// Output:
}

func ExampleAssignmentExpression_div() {
	fmt.Println(exampleAST(77, "int f() { x /= y; }"))
	// Output:
}

func ExampleAssignmentExpression_mod() {
	fmt.Println(exampleAST(78, "int f() { x %= y; }"))
	// Output:
}

func ExampleAssignmentExpression_add() {
	fmt.Println(exampleAST(79, "int f() { x += y; }"))
	// Output:
}

func ExampleAssignmentExpression_sub() {
	fmt.Println(exampleAST(80, "int f() { x -= y; }"))
	// Output:
}

func ExampleAssignmentExpression_lsh() {
	fmt.Println(exampleAST(81, "int f() { x <<= y; }"))
	// Output:
}

func ExampleAssignmentExpression_rsh() {
	fmt.Println(exampleAST(82, "int f() { x >>= y; }"))
	// Output:
}

func ExampleAssignmentExpression_and() {
	fmt.Println(exampleAST(83, "int f() { x &= y; }"))
	// Output:
}

func ExampleAssignmentExpression_xor() {
	fmt.Println(exampleAST(84, "int f() { x ^= y; }"))
	// Output:
}

func ExampleAssignmentExpression_or() {
	fmt.Println(exampleAST(85, "int f() { x |= y; }"))
	// Output:
}

func ExampleAtomicTypeSpecifier_case0() {
	fmt.Println(exampleAST(166, "_Atomic(int) i;"))
	// Output:
}

func ExampleAttributeSpecifier_case0() {
	fmt.Println(exampleAST(276, "int i __attribute__((a));"))
	// Output:
}

func ExampleAttributeSpecifierList_case0() {
	fmt.Println(exampleAST(277, "int i __attribute__((a));"))
	// Output:
}

func ExampleAttributeSpecifierList_case1() {
	fmt.Println(exampleAST(278, "int i __attribute__((a)) __attribute__((b));"))
	// Output:
}

func ExampleAttributeValue_ident() {
	fmt.Println(exampleAST(272, "int i __attribute__((a));"))
	// Output:
}

func ExampleAttributeValue_expr() {
	fmt.Println(exampleAST(273, "int i __attribute__((a(b)));"))
	// Output:
}

func ExampleAttributeValueList_case0() {
	fmt.Println(exampleAST(274, "int i __attribute__((a));"))
	// Output:
}

func ExampleAttributeValueList_case1() {
	fmt.Println(exampleAST(275, "int i __attribute__((a, b));"))
	// Output:
}

func ExampleBlockItem_decl() {
	fmt.Println(exampleAST(234, "int f() { int i; }"))
	// Output:
}

func ExampleBlockItem_label() {
	fmt.Println(exampleAST(235, "int f() { __label__ L; int i; }"))
	// Output:
}

func ExampleBlockItem_stmt() {
	fmt.Println(exampleAST(236, "int f() { g(); }"))
	// Output:
}

func ExampleBlockItem_funcDef() {
	fmt.Println(exampleAST(237, "int f() { int g() {} }"))
	// Output:
}

func ExampleBlockItemList_case0() {
	fmt.Println(exampleAST(232, "int f() { int i; }"))
	// Output:
}

func ExampleBlockItemList_case1() {
	fmt.Println(exampleAST(233, "int f() { int i; double j; }"))
	// Output:
}

func ExampleCastExpression_cast() {
	fmt.Println(exampleAST(43, "int i = (__attribute__((a)) int)3.14;"))
	// Output:
}

func ExampleCompoundStatement_case0() {
	fmt.Println(exampleAST(230, "int f() { __label__ L; int i; }"))
	// Output:
}

func ExampleConditionalExpression_cond() {
	fmt.Println(exampleAST(73, "int i = x ? y : z;"))
	// Output:
}

func ExampleConstantExpression_case0() {
	fmt.Println(exampleAST(88, "struct { int i:3; };"))
	// Output:
}

func ExampleDeclaration_decl() {
	fmt.Println(exampleAST(89, "int i, j __attribute__((a));"))
	// Output:
}

func ExampleDeclaration_assert() {
	fmt.Println(exampleAST(90, "_Static_assert(x > y, \"abc\")"))
	// Output:
}

func ExampleDeclaration_auto() {
	fmt.Println(exampleAST(91, "__auto_type x = y;"))
	// Output:
}

func ExampleDeclarationList_case0() {
	fmt.Println(exampleAST(258, "int f(i) int i; {}"))
	// Output:
}

func ExampleDeclarationList_case1() {
	fmt.Println(exampleAST(259, "int f(i, j) int i; int j; {}"))
	// Output:
}

func ExampleDeclarationSpecifiers_storage() {
	fmt.Println(exampleAST(93, "__attribute__((a)) static int i;"))
	// Output:
}

func ExampleDeclarationSpecifiers_typeSpec() {
	fmt.Println(exampleAST(94, "int i;"))
	// Output:
}

func ExampleDeclarationSpecifiers_typeQual() {
	fmt.Println(exampleAST(95, "volatile int i;"))
	// Output:
}

func ExampleDeclarationSpecifiers_func() {
	fmt.Println(exampleAST(96, "inline int f() {}"))
	// Output:
}

func ExampleDeclarationSpecifiers_alignSpec() {
	fmt.Println(exampleAST(97, "_Alignas(double) int i;"))
	// Output:
}

func ExampleDeclarationSpecifiers_attr() {
	fmt.Println(exampleAST(98, "__attribute__((a)) int i;"))
	// Output:
}

func ExampleDeclarator_case0() {
	fmt.Println(exampleAST(175, "int *p;"))
	// Output:
}

func ExampleDesignation_case0() {
	fmt.Println(exampleAST(212, "int a[] = { [42] = 314 };"))
	// Output:
}

func ExampleDesignator_index() {
	fmt.Println(exampleAST(215, "int a[] = { [42] = 314 };"))
	// Output:
}

func ExampleDesignator_index2() {
	fmt.Println(exampleAST(216, "int a[] = { [42 ... 278] = 314 };"))
	// Output:
}

func ExampleDesignator_field() {
	fmt.Println(exampleAST(217, "struct t s = { .fld = 314 };"))
	// Output:
}

func ExampleDesignator_field2() {
	fmt.Println(exampleAST(218, "struct t s = { fld: 314 };"))
	// Output:
}

func ExampleDesignatorList_case0() {
	fmt.Println(exampleAST(213, "int a[] = { [42] = 314 };"))
	// Output:
}

func ExampleDesignatorList_case1() {
	fmt.Println(exampleAST(214, "int a[100][] = { [42][12] = 314 };"))
	// Output:
}

func ExampleDirectAbstractDeclarator_decl() {
	fmt.Println(exampleAST(202, "void f(int(*));"))
	// Output:
}

func ExampleDirectAbstractDeclarator_arr() {
	fmt.Println(exampleAST(203, "void f(int[const 42]);"))
	// Output:
}

func ExampleDirectAbstractDeclarator_staticArr() {
	fmt.Println(exampleAST(204, "void f(int[static const 42]);"))
	// Output:
}

func ExampleDirectAbstractDeclarator_arrStatic() {
	fmt.Println(exampleAST(205, "void f(int[const static 42]);"))
	// Output:
}

func ExampleDirectAbstractDeclarator_arrStar() {
	fmt.Println(exampleAST(206, "void f(int[*]);"))
	// Output:
}

func ExampleDirectAbstractDeclarator_func() {
	fmt.Println(exampleAST(207, "void f(int(char));"))
	// Output:
}

func ExampleDirectDeclarator_ident() {
	fmt.Println(exampleAST(178, "int i;"))
	// Output:
}

func ExampleDirectDeclarator_decl() {
	fmt.Println(exampleAST(179, "int (f);"))
	// Output:
}

func ExampleDirectDeclarator_arr() {
	fmt.Println(exampleAST(180, "int i[const 42];"))
	// Output:
}

func ExampleDirectDeclarator_staticArr() {
	fmt.Println(exampleAST(181, "int i[static const 42];"))
	// Output:
}

func ExampleDirectDeclarator_arrStatic() {
	fmt.Println(exampleAST(182, "int i[const static 42];"))
	// Output:
}

func ExampleDirectDeclarator_star() {
	fmt.Println(exampleAST(183, "int i[const *];"))
	// Output:
}

func ExampleDirectDeclarator_funcParam() {
	fmt.Println(exampleAST(184, "int f(int i);"))
	// Output:
}

func ExampleDirectDeclarator_funcIdent() {
	fmt.Println(exampleAST(185, "int f(a);"))
	// Output:
}

func ExampleEnumSpecifier_def() {
	fmt.Println(exampleAST(159, "enum e : char {a};"))
	// Output:
}

func ExampleEnumSpecifier_tag() {
	fmt.Println(exampleAST(160, "enum e : char i;"))
	// Output:
}

func ExampleEnumTypeSpecifier_case0() {
	fmt.Println(exampleAST(161, "enum : char {a} b;"))
	// Output:
}

func ExampleEnumerator_ident() {
	fmt.Println(exampleAST(164, "enum e {a};"))
	// Output:
}

func ExampleEnumerator_expr() {
	fmt.Println(exampleAST(165, "enum e {a = 42};"))
	// Output:
}

func ExampleEnumeratorList_case0() {
	fmt.Println(exampleAST(162, "enum e {a};"))
	// Output:
}

func ExampleEnumeratorList_case1() {
	fmt.Println(exampleAST(163, "enum e {a, b};"))
	// Output:
}

func ExampleEqualityExpression_eq() {
	fmt.Println(exampleAST(60, "int i = x == y;"))
	// Output:
}

func ExampleEqualityExpression_neq() {
	fmt.Println(exampleAST(61, "int i = x != y;"))
	// Output:
}

func ExampleExclusiveOrExpression_xor() {
	fmt.Println(exampleAST(65, "int i = x^y;"))
	// Output:
}

func ExampleExpressionList_assign() {
	fmt.Println(exampleAST(86, "int f() { i = x; };"))
	// Output:
}

func ExampleExpressionList_comma() {
	fmt.Println(exampleAST(87, "int f() { x, y; };"))
	// Output:
}

func ExampleExpressionStatement_case0() {
	fmt.Println(exampleAST(238, "int f() { g(); }"))
	// Output:
}

func ExampleExternalDeclaration_funcDef() {
	fmt.Println(exampleAST(253, "int f() {}"))
	// Output:
}

func ExampleExternalDeclaration_decl() {
	fmt.Println(exampleAST(254, "register int i __asm__(\"r0\");"))
	// Output:
}

func ExampleExternalDeclaration_asmStmt() {
	fmt.Println(exampleAST(255, "__asm__(\"nop\");"))
	// Output:
}

func ExampleExternalDeclaration_empty() {
	fmt.Println(exampleAST(256, ";"))
	// Output:
}

func ExampleFunctionDefinition_case0() {
	fmt.Println(exampleAST(257, "int f() {}"))
	// Output:
}

func ExampleFunctionSpecifier_inline() {
	fmt.Println(exampleAST(173, "inline int f() {}"))
	// Output:
}

func ExampleFunctionSpecifier_noreturn() {
	fmt.Println(exampleAST(174, "_Noreturn int f() {}"))
	// Output:
}

func ExampleGenericAssociation_type() {
	fmt.Println(exampleAST(14, "int i = _Generic(x, int: y)(42);"))
	// Output:
}

func ExampleGenericAssociation_default() {
	fmt.Println(exampleAST(15, "int i = _Generic(x, default: y)(42);"))
	// Output:
}

func ExampleGenericAssociationList_case0() {
	fmt.Println(exampleAST(12, "int i = _Generic(x, int: y)(42);"))
	// Output:
}

func ExampleGenericAssociationList_case1() {
	fmt.Println(exampleAST(13, "int i = _Generic(x, int: y, float: z)(42);"))
	// Output:
}

func ExampleGenericSelection_case0() {
	fmt.Println(exampleAST(11, "int i = _Generic(x, int: y)(42);"))
	// Output:
}

func ExampleIdentifierList_case0() {
	fmt.Println(exampleAST(197, "int f(i) int i; {}"))
	// Output:
}

func ExampleIdentifierList_case1() {
	fmt.Println(exampleAST(198, "int f(i, j) int i, j; {}"))
	// Output:
}

func ExampleInclusiveOrExpression_or() {
	fmt.Println(exampleAST(67, "int i = x|y;"))
	// Output:
}

func ExampleInitDeclarator_decl() {
	fmt.Println(exampleAST(101, "register int i __asm__(\"r0\");"))
	// Output:
}

func ExampleInitDeclarator_init() {
	fmt.Println(exampleAST(102, "register int i __asm__(\"r0\") = x;"))
	// Output:
}

func ExampleInitDeclaratorList_case0() {
	fmt.Println(exampleAST(99, "int i;"))
	// Output:
}

func ExampleInitDeclaratorList_case1() {
	fmt.Println(exampleAST(100, "int i, __attribute__((a)) j;"))
	// Output:
}

func ExampleInitializer_expr() {
	fmt.Println(exampleAST(208, "int i = x;"))
	// Output:
}

func ExampleInitializer_initList() {
	fmt.Println(exampleAST(209, "int i[] = { x };"))
	// Output:
}

func ExampleInitializerList_case0() {
	fmt.Println(exampleAST(210, "int i[] = { [10] = x };"))
	// Output:
}

func ExampleInitializerList_case1() {
	fmt.Println(exampleAST(211, "int i[] = { [10] = x, [20] = y };"))
	// Output:
}

func ExampleIterationStatement_while() {
	fmt.Println(exampleAST(242, "int f() { while(x) y(); }"))
	// Output:
}

func ExampleIterationStatement_do() {
	fmt.Println(exampleAST(243, "int f() { do x(); while(y); }"))
	// Output:
}

func ExampleIterationStatement_for() {
	fmt.Println(exampleAST(244, "int f() { for( i = 0; i < 10; i++) x(); }"))
	// Output:
}

func ExampleIterationStatement_forDecl() {
	fmt.Println(exampleAST(245, "int f() { for( int i = 0; i < 10; i++) x(); }"))
	// Output:
}

func ExampleJumpStatement_goto() {
	fmt.Println(exampleAST(246, "int f() { L: goto L; }"))
	// Output:
}

func ExampleJumpStatement_gotoExpr() {
	fmt.Println(exampleAST(247, "int f() { L: x(); void *p = &&L; goto *p; }"))
	// Output:
}

func ExampleJumpStatement_continue() {
	fmt.Println(exampleAST(248, "int f() { for(;;) if (i) continue; }"))
	// Output:
}

func ExampleJumpStatement_break() {
	fmt.Println(exampleAST(249, "int f() { for(;;) if (i) break; }"))
	// Output:
}

func ExampleJumpStatement_return() {
	fmt.Println(exampleAST(250, "int f() { if (i) return x; }"))
	// Output:
}

func ExampleLabelDeclaration_case0() {
	fmt.Println(exampleAST(231, "int f() { __label__ L, M; L: x(); M: y(); }"))
	// Output:
}

func ExampleLabeledStatement_label() {
	fmt.Println(exampleAST(226, "int f() { L: goto L; }"))
	// Output:
}

func ExampleLabeledStatement_caseLabel() {
	fmt.Println(exampleAST(227, "int f() { switch(i) case 42: x(); }"))
	// Output:
}

func ExampleLabeledStatement_range() {
	fmt.Println(exampleAST(228, "int f() { switch(i) case 42 ... 56: x(); }"))
	// Output:
}

func ExampleLabeledStatement_default() {
	fmt.Println(exampleAST(229, "int f() { switch(i) default: x(); }"))
	// Output:
}

func ExampleLogicalAndExpression_lAnd() {
	fmt.Println(exampleAST(69, "int i = x && y;"))
	// Output:
}

func ExampleLogicalOrExpression_lOr() {
	fmt.Println(exampleAST(71, "int i = x || y;"))
	// Output:
}

func ExampleMultiplicativeExpression_mul() {
	fmt.Println(exampleAST(45, "int i = x * y;"))
	// Output:
}

func ExampleMultiplicativeExpression_div() {
	fmt.Println(exampleAST(46, "int i = x / y;"))
	// Output:
}

func ExampleMultiplicativeExpression_mod() {
	fmt.Println(exampleAST(47, "int i = x % y;"))
	// Output:
}

func ExampleParameterDeclaration_decl() {
	fmt.Println(exampleAST(195, "int f(int i __attribute__((a))) {}"))
	// Output:
}

func ExampleParameterDeclaration_abstract() {
	fmt.Println(exampleAST(196, "int f(int*) {}"))
	// Output:
}

func ExampleParameterList_case0() {
	fmt.Println(exampleAST(193, "int f(int i) {}"))
	// Output:
}

func ExampleParameterList_case1() {
	fmt.Println(exampleAST(194, "int f(int i, int j) {}"))
	// Output:
}

func ExampleParameterTypeList_list() {
	fmt.Println(exampleAST(191, "int f(int i) {}"))
	// Output:
}

func ExampleParameterTypeList_var() {
	fmt.Println(exampleAST(192, "int f(int i, ...) {}"))
	// Output:
}

func ExamplePointer_typeQual() {
	fmt.Println(exampleAST(186, "int *p;"))
	// Output:
}

func ExamplePointer_ptr() {
	fmt.Println(exampleAST(187, "int **p;"))
	// Output:
}

func ExamplePointer_block() {
	fmt.Println(exampleAST(188, "int atexit_b(void (^ _Nonnull)(void));"))
	// Output:
}

func ExamplePostfixExpression_index() {
	fmt.Println(exampleAST(17, "int i = x[y];"))
	// Output:
}

func ExamplePostfixExpression_call() {
	fmt.Println(exampleAST(18, "int i = x(y);"))
	// Output:
}

func ExamplePostfixExpression_select() {
	fmt.Println(exampleAST(19, "int i = x.y;"))
	// Output:
}

func ExamplePostfixExpression_pSelect() {
	fmt.Println(exampleAST(20, "int i = x->y;"))
	// Output:
}

func ExamplePostfixExpression_inc() {
	fmt.Println(exampleAST(21, "int i = x++;"))
	// Output:
}

func ExamplePostfixExpression_dec() {
	fmt.Println(exampleAST(22, "int i = x--;"))
	// Output:
}

func ExamplePostfixExpression_complit() {
	fmt.Println(exampleAST(23, "int i = (int[]){y};"))
	// Output:
}

func ExamplePrimaryExpression_ident() {
	fmt.Println(exampleAST(1, "int i = x;"))
	// Output:
}

func ExamplePrimaryExpression_int() {
	fmt.Println(exampleAST(2, "int i = 42;"))
	// Output:
}

func ExamplePrimaryExpression_float() {
	fmt.Println(exampleAST(3, "int i = 3.14;"))
	// Output:
}

func ExamplePrimaryExpression_char() {
	fmt.Println(exampleAST(4, "int i = 'x';"))
	// Output:
}

func ExamplePrimaryExpression_lChar() {
	fmt.Println(exampleAST(5, "int i = L'x';"))
	// Output:
}

func ExamplePrimaryExpression_string() {
	fmt.Println(exampleAST(6, "char *c = \"x\" \"y\";"))
	// Output:
}

func ExamplePrimaryExpression_lString() {
	fmt.Println(exampleAST(7, "char *c = L\"x\" L\"y\";"))
	// Output:
}

func ExamplePrimaryExpression_expr() {
	fmt.Println(exampleAST(8, "int i = (x+y);"))
	// Output:
}

func ExamplePrimaryExpression_stmt() {
	fmt.Println(exampleAST(9, "int i = ({x();});"))
	// Output:
}

func ExamplePrimaryExpression_generic() {
	fmt.Println(exampleAST(10, "int i = _Generic(x, int: y)(42);"))
	// Output:
}

func ExampleRelationalExpression_lt() {
	fmt.Println(exampleAST(55, "int i = x < y;"))
	// Output:
}

func ExampleRelationalExpression_gt() {
	fmt.Println(exampleAST(56, "int i = x > y;"))
	// Output:
}

func ExampleRelationalExpression_leq() {
	fmt.Println(exampleAST(57, "int i = x <= y;"))
	// Output:
}

func ExampleRelationalExpression_geq() {
	fmt.Println(exampleAST(58, "int i = x >= y;"))
	// Output:
}

func ExampleSelectionStatement_if() {
	fmt.Println(exampleAST(239, "int f() { if(x) y(); }"))
	// Output:
}

func ExampleSelectionStatement_ifElse() {
	fmt.Println(exampleAST(240, "int f() { if(x) y(); else z(); }"))
	// Output:
}

func ExampleSelectionStatement_switch() {
	fmt.Println(exampleAST(241, "int f() { switch(i) case 42: x(); }"))
	// Output:
}

func ExampleShiftExpression_lsh() {
	fmt.Println(exampleAST(52, "int i = x << y;"))
	// Output:
}

func ExampleShiftExpression_rsh() {
	fmt.Println(exampleAST(53, "int i = x >> y;"))
	// Output:
}

func ExampleSpecifierQualifierList_typeSpec() {
	fmt.Println(exampleAST(152, "struct {int i;};"))
	// Output:
}

func ExampleSpecifierQualifierList_typeQual() {
	fmt.Println(exampleAST(153, "struct {const int i;};"))
	// Output:
}

func ExampleSpecifierQualifierList_alignSpec() {
	fmt.Println(exampleAST(154, "struct {_Alignas(double) int i;};"))
	// Output:
}

func ExampleStatement_labeled() {
	fmt.Println(exampleAST(219, "int f() { L: x(); }"))
	// Output:
}

func ExampleStatement_compound() {
	fmt.Println(exampleAST(220, "int f() { { y(); } }"))
	// Output:
}

func ExampleStatement_expr() {
	fmt.Println(exampleAST(221, "int f() { __attribute__((a)); }"))
	// Output:
}

func ExampleStatement_selection() {
	fmt.Println(exampleAST(222, "int f() { if(x) y(); }"))
	// Output:
}

func ExampleStatement_iteration() {
	fmt.Println(exampleAST(223, "int f() { for(;;) x(); }"))
	// Output:
}

func ExampleStatement_jump() {
	fmt.Println(exampleAST(224, "int f() { return x; }"))
	// Output:
}

func ExampleStatement_asm() {
	fmt.Println(exampleAST(225, "int f() { __asm__(\"nop\"); }"))
	// Output:
}

func ExampleStaticAssertDeclaration_case0() {
	fmt.Println(exampleAST(92, "_Static_assert(x > y, \"abc\")"))
	// Output:
}

func ExampleStorageClassSpecifier_typedef() {
	fmt.Println(exampleAST(103, "typedef int int_t;"))
	// Output:
}

func ExampleStorageClassSpecifier_extern() {
	fmt.Println(exampleAST(104, "extern int i;"))
	// Output:
}

func ExampleStorageClassSpecifier_static() {
	fmt.Println(exampleAST(105, "static int i;"))
	// Output:
}

func ExampleStorageClassSpecifier_auto() {
	fmt.Println(exampleAST(106, "auto int i;"))
	// Output:
}

func ExampleStorageClassSpecifier_register() {
	fmt.Println(exampleAST(107, "register int i;"))
	// Output:
}

func ExampleStorageClassSpecifier_threadLocal() {
	fmt.Println(exampleAST(108, "_Thread_local int i;"))
	// Output:
}

func ExampleStorageClassSpecifier_declspec() {
	fmt.Println(exampleAST(109, "__declspec(foo) int i;"))
	// Output:
}

func ExampleStructDeclaration_decl() {
	fmt.Println(exampleAST(150, "struct{ int i __attribute__((a)); };"))
	// Output:
}

func ExampleStructDeclaration_assert() {
	fmt.Println(exampleAST(151, "struct{ _Static_assert(x > y, \"abc\"); };"))
	// Output:
}

func ExampleStructDeclarationList_case0() {
	fmt.Println(exampleAST(148, "struct{ __attribute__((a)) int i; };"))
	// Output:
}

func ExampleStructDeclarationList_case1() {
	fmt.Println(exampleAST(149, "struct{ int i; double d; };"))
	// Output:
}

func ExampleStructDeclarator_decl() {
	fmt.Println(exampleAST(157, "struct{ int i; };"))
	// Output:
}

func ExampleStructDeclarator_bitField() {
	fmt.Println(exampleAST(158, "struct{ int i:3; };"))
	// Output:
}

func ExampleStructDeclaratorList_case0() {
	fmt.Println(exampleAST(155, "struct{ int i; };"))
	// Output:
}

func ExampleStructDeclaratorList_case1() {
	fmt.Println(exampleAST(156, "struct{ int i, j; };"))
	// Output:
}

func ExampleStructOrUnion_struct() {
	fmt.Println(exampleAST(146, "struct { int i; } s;"))
	// Output:
}

func ExampleStructOrUnion_union() {
	fmt.Println(exampleAST(147, "union { int i; double d; } u;"))
	// Output:
}

func ExampleStructOrUnionSpecifier_def() {
	fmt.Println(exampleAST(144, "struct s { int i; } __attribute__((a));"))
	// Output:
}

func ExampleStructOrUnionSpecifier_tag() {
	fmt.Println(exampleAST(145, "struct __attribute__((a)) s v;"))
	// Output:
}

func ExampleTranslationUnit_case0() {
	fmt.Println(exampleAST(251, "int i;"))
	// Output:
}

func ExampleTranslationUnit_case1() {
	fmt.Println(exampleAST(252, "int i; int j;"))
	// Output:
}

func ExampleTypeName_case0() {
	fmt.Println(exampleAST(199, "int i = (int)x;"))
	// Output:
}

func ExampleTypeQualifier_const() {
	fmt.Println(exampleAST(167, "const int i;"))
	// Output:
}

func ExampleTypeQualifier_restrict() {
	fmt.Println(exampleAST(168, "restrict int i;"))
	// Output:
}

func ExampleTypeQualifier_volatile() {
	fmt.Println(exampleAST(169, "volatile int i;"))
	// Output:
}

func ExampleTypeQualifier_atomic() {
	fmt.Println(exampleAST(170, "_Atomic int i;"))
	// Output:
}

func ExampleTypeQualifier_nonnull() {
	fmt.Println(exampleAST(171, "_Nonnull int i;"))
	// Output:
}

func ExampleTypeQualifier_attr() {
	fmt.Println(exampleAST(172, "struct { __attribute__((a)) int i; };"))
	// Output:
}

func ExampleTypeQualifiers_typeQual() {
	fmt.Println(exampleAST(189, "int * __attribute__((a)) const i;"))
	// Output:
}

func ExampleTypeQualifiers_case1() {
	fmt.Println(exampleAST(190, "int * const volatile i;"))
	// Output:
}

func ExampleTypeSpecifier_void() {
	fmt.Println(exampleAST(110, "void i();"))
	// Output:
}

func ExampleTypeSpecifier_char() {
	fmt.Println(exampleAST(111, "char i;"))
	// Output:
}

func ExampleTypeSpecifier_short() {
	fmt.Println(exampleAST(112, "short i;"))
	// Output:
}

func ExampleTypeSpecifier_int() {
	fmt.Println(exampleAST(113, "int i;"))
	// Output:
}

func ExampleTypeSpecifier_int8() {
	fmt.Println(exampleAST(114, "__int8 i;"))
	// Output:
}

func ExampleTypeSpecifier_int16() {
	fmt.Println(exampleAST(115, "__int16 i;"))
	// Output:
}

func ExampleTypeSpecifier_int32() {
	fmt.Println(exampleAST(116, "__int32 i;"))
	// Output:
}

func ExampleTypeSpecifier_int64() {
	fmt.Println(exampleAST(117, "__int64 i;"))
	// Output:
}

func ExampleTypeSpecifier_int128() {
	fmt.Println(exampleAST(118, "__int128 i;"))
	// Output:
}

func ExampleTypeSpecifier_uint128() {
	fmt.Println(exampleAST(119, "__uint128_t i;"))
	// Output:
}

func ExampleTypeSpecifier_long() {
	fmt.Println(exampleAST(120, "long i;"))
	// Output:
}

func ExampleTypeSpecifier_float() {
	fmt.Println(exampleAST(121, "float i;"))
	// Output:
}

func ExampleTypeSpecifier_float16() {
	fmt.Println(exampleAST(122, "_Float16 i;"))
	// Output:
}

func ExampleTypeSpecifier_decimal32() {
	fmt.Println(exampleAST(123, "_Decimal32 i;"))
	// Output:
}

func ExampleTypeSpecifier_decimal64() {
	fmt.Println(exampleAST(124, "_Decimal64 i;"))
	// Output:
}

func ExampleTypeSpecifier_decimal128() {
	fmt.Println(exampleAST(125, "_Decimal128 i;"))
	// Output:
}

func ExampleTypeSpecifier_float128() {
	fmt.Println(exampleAST(126, "_Float128 i;"))
	// Output:
}

func ExampleTypeSpecifier_float128x() {
	fmt.Println(exampleAST(127, "_Float128x i;"))
	// Output:
}

func ExampleTypeSpecifier_double() {
	fmt.Println(exampleAST(128, "double i;"))
	// Output:
}

func ExampleTypeSpecifier_signed() {
	fmt.Println(exampleAST(129, "signed i;"))
	// Output:
}

func ExampleTypeSpecifier_unsigned() {
	fmt.Println(exampleAST(130, "unsigned i;"))
	// Output:
}

func ExampleTypeSpecifier_bool() {
	fmt.Println(exampleAST(131, "_Bool i;"))
	// Output:
}

func ExampleTypeSpecifier_complex() {
	fmt.Println(exampleAST(132, "_Complex i;"))
	// Output:
}

func ExampleTypeSpecifier_imaginary() {
	fmt.Println(exampleAST(133, "_Imaginary i;"))
	// Output:
}

func ExampleTypeSpecifier_structOrUnion() {
	fmt.Println(exampleAST(134, "struct s i;"))
	// Output:
}

func ExampleTypeSpecifier_enum() {
	fmt.Println(exampleAST(135, "enum e i;"))
	// Output:
}

func ExampleTypeSpecifier_typeName() {
	fmt.Println(exampleAST(136, "typedef int T; T i;"))
	// Output:
}

func ExampleTypeSpecifier_typeofExpr() {
	fmt.Println(exampleAST(137, "typeof(42) i;"))
	// Output:
}

func ExampleTypeSpecifier_typeofType() {
	fmt.Println(exampleAST(138, "typedef int T; typeof(T) i;"))
	// Output:
}

func ExampleTypeSpecifier_atomic() {
	fmt.Println(exampleAST(139, "_Atomic(int) i;"))
	// Output:
}

func ExampleTypeSpecifier_float32() {
	fmt.Println(exampleAST(140, "_Float32 i;"))
	// Output:
}

func ExampleTypeSpecifier_float64() {
	fmt.Println(exampleAST(141, "_Float64 i;"))
	// Output:
}

func ExampleTypeSpecifier_float32x() {
	fmt.Println(exampleAST(142, "_Float32x i;"))
	// Output:
}

func ExampleTypeSpecifier_float64x() {
	fmt.Println(exampleAST(143, "_Float64x i;"))
	// Output:
}

func ExampleUnaryExpression_inc() {
	fmt.Println(exampleAST(27, "int i = ++x;"))
	// Output:
}

func ExampleUnaryExpression_dec() {
	fmt.Println(exampleAST(28, "int i = --x;"))
	// Output:
}

func ExampleUnaryExpression_addrof() {
	fmt.Println(exampleAST(29, "int *i = &x;"))
	// Output:
}

func ExampleUnaryExpression_deref() {
	fmt.Println(exampleAST(30, "int i = *x;"))
	// Output:
}

func ExampleUnaryExpression_plus() {
	fmt.Println(exampleAST(31, "int i = +x;"))
	// Output:
}

func ExampleUnaryExpression_minus() {
	fmt.Println(exampleAST(32, "int i = -x;"))
	// Output:
}

func ExampleUnaryExpression_cpl() {
	fmt.Println(exampleAST(33, "int i = ~x;"))
	// Output:
}

func ExampleUnaryExpression_not() {
	fmt.Println(exampleAST(34, "int i = !x;"))
	// Output:
}

func ExampleUnaryExpression_sizeofExpr() {
	fmt.Println(exampleAST(35, "int i = sizeof x;"))
	// Output:
}

func ExampleUnaryExpression_sizeofType() {
	fmt.Println(exampleAST(36, "int i = sizeof(int);"))
	// Output:
}

func ExampleUnaryExpression_labelAddr() {
	fmt.Println(exampleAST(37, "int f() { L: &&L; }"))
	// Output:
}

func ExampleUnaryExpression_alignofExpr() {
	fmt.Println(exampleAST(38, "int i = _Alignof(x);"))
	// Output:
}

func ExampleUnaryExpression_alignofType() {
	fmt.Println(exampleAST(39, "int i = _Alignof(int);"))
	// Output:
}

func ExampleUnaryExpression_imag() {
	fmt.Println(exampleAST(40, "double i = __imag__ x;"))
	// Output:
}

func ExampleUnaryExpression_real() {
	fmt.Println(exampleAST(41, "double i = __real__ x;"))
	// Output:
}
